# Generated by Django 6.0.4 on 2026-04-24 03:39

import django.db.models.deletion
import passport.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0004_classlevel_internal_canonical_grade_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('credential_type', models.CharField(choices=[('badge', 'Badge'), ('certificate', 'Certificate')], default='badge', max_length=20)),
                ('level', models.CharField(blank=True, help_text='e.g. P7, S3, Beginner…', max_length=40)),
                ('criteria', models.TextField(blank=True, help_text='Human-readable criteria — what earned this.')),
                ('issuer_type', models.CharField(choices=[('maple', 'Maple Platform'), ('institution', 'Institution'), ('teacher', 'Teacher')], default='maple', max_length=20)),
                ('is_verifiable', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='curriculum.subject')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='LearningPassport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('parent_only', 'Parent Only'), ('shareable', 'Shareable')], default='private', max_length=20)),
                ('public_share_token', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('headline', models.CharField(blank=True, help_text='e.g. "S3 · Maths & Physics track"', max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learning_passport', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PassportEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('certificate', 'Certificate'), ('badge', 'Badge'), ('project', 'Project'), ('assessment', 'Assessment'), ('teacher_feedback', 'Teacher Feedback'), ('exam_report', 'Exam Report'), ('peer_contribution', 'Peer Contribution'), ('track_completion', 'Track Completion')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('evidence_url', models.URLField(blank=True, help_text='In-platform deep link to the evidence.')),
                ('related_object_type', models.CharField(blank=True, max_length=60)),
                ('related_object_id', models.CharField(blank=True, max_length=64)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('passport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='passport.learningpassport')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='IssuedCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('related_track_id', models.UUIDField(blank=True, null=True)),
                ('related_project_id', models.UUIDField(blank=True, null=True)),
                ('related_assessment_id', models.CharField(blank=True, max_length=64)),
                ('verification_code', models.CharField(default=passport.models._make_verification_code, max_length=40, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_instances', to='passport.credential')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_credentials_given', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issued_at'],
                'indexes': [models.Index(fields=['student', 'issued_at'], name='passport_is_student_9fdf8b_idx'), models.Index(fields=['verification_code'], name='passport_is_verific_362a4f_idx')],
            },
        ),
    ]
