# Generated by Django 4.2.29 on 2026-04-02 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_label', models.CharField(help_text='e.g. NCDC 2021 Update', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('release_date', models.DateField()),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='curriculum.curriculumtrack')),
            ],
        ),
        migrations.CreateModel(
            name='ResourceQualityReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_resource_ref', models.CharField(help_text='UUID or reference to the specific teaching asset.', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Officially Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('compliance_score', models.IntegerField(default=0, help_text='Scale 0-100 NCDC alignment score.')),
                ('reviewer_notes', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TopicCompetency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='National competency or learning objective expected at this topic.')),
                ('code', models.CharField(blank=True, help_text='e.g. BIO.S1.01', max_length=50, null=True)),
                ('curriculum_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencies', to='curriculum.curriculumversion')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencies', to='curriculum.topic')),
            ],
        ),
    ]
