# Generated by Django 4.2.29 on 2026-04-06 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_subtopic_term_templatelesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_label', models.CharField(help_text='e.g. "2024" or "2024/2025"', max_length=20, unique=True)),
                ('start_date', models.DateField(blank=True, help_text='First day of the academic year', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Last day of the academic year', null=True)),
                ('is_current', models.BooleanField(default=False, help_text='Mark the currently active academic year')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Academic Year',
                'verbose_name_plural': 'Academic Years',
                'ordering': ['-year_label'],
            },
        ),
    ]
