# Generated by Django 4.2.29 on 2026-04-08 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_academicyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='classlevel',
            name='internal_canonical_grade',
            field=models.IntegerField(default=0, help_text='Standardized grade mapping anchor (e.g. 4 for P4/Grade 4, 8 for S1/Grade 8)'),
        ),
        migrations.AddField(
            model_name='educationlevel',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Flags this level as a primary education tier'),
        ),
    ]
