from django.db import models

class ParentStudentLink(models.Model):
    parent_profile = models.ForeignKey('accounts.ParentProfile', on_delete=models.CASCADE, related_name='student_links')
    student_profile = models.ForeignKey('accounts.StudentProfile', on_delete=models.CASCADE, related_name='parent_links')
    consent_status = models.CharField(max_length=50, default='pending')
    linked_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Link: {self.parent_profile.user.full_name} -> {self.student_profile.user.full_name}"

class WeeklySummary(models.Model):
    link = models.ForeignKey(ParentStudentLink, on_delete=models.CASCADE, related_name='summaries')
    week_date = models.DateField()
    ai_generated_narrative = models.TextField(help_text="Warm, encouraging summary text generated by LLM")
    is_read = models.BooleanField(default=False)

    def __str__(self):
        return f"Summary {self.week_date} for {self.link}"

class RiskAlert(models.Model):
    SEVERITY_CHOICES = [
        ('low', 'Low'),
        ('medium', 'Medium'),
        ('high', 'High'),
        ('critical', 'Critical'),
    ]
    student = models.ForeignKey('accounts.User', on_delete=models.CASCADE, related_name='risk_alerts')
    trigger_reason = models.CharField(max_length=255)
    severity = models.CharField(max_length=20, choices=SEVERITY_CHOICES)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Risk Alert: {self.student.full_name} ({self.severity})"
