# Generated by Django 4.2.29 on 2026-04-08 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_classlevel_internal_canonical_grade_and_more'),
        ('institutions', '0004_institution_grade_offerings_institution_school_level'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableslot',
            name='is_draft',
            field=models.BooleanField(default=False, help_text='Draft slots are visible only for prep/allocation reviews.'),
        ),
        migrations.AddField(
            model_name='timetableslot',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='curriculum.subject'),
        ),
        migrations.CreateModel(
            name='TimetableConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conflict_type', models.CharField(choices=[('teacher', 'Teacher Overlap'), ('room', 'Room Overlap'), ('class', 'Class Overlap')], max_length=20)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_conflicts', to='institutions.institution')),
                ('slot_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflict_associations_1', to='scheduling.timetableslot')),
                ('slot_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflict_associations_2', to='scheduling.timetableslot')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.academicterm')),
            ],
        ),
    ]
