# Generated by Django 4.2.29 on 2026-04-01 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduling', '0001_initial'),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyregister',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_registers', to='scheduling.academicterm'),
        ),
        migrations.AlterUniqueTogether(
            name='lessonattendance',
            unique_together={('lesson', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='dailyregister',
            unique_together={('student', 'record_date')},
        ),
    ]
