# Generated by Django 4.2.29 on 2026-04-06 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('institutions', '0001_initial'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gl_accounts', to='institutions.institution'),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cost_centers', to='institutions.institution'),
        ),
        migrations.AddField(
            model_name='discountrule',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount_rules', to='institutions.institution'),
        ),
        migrations.AddField(
            model_name='financialperiod',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financial_periods', to='institutions.institution'),
        ),
        migrations.AddField(
            model_name='financialperiod',
            name='is_soft_closed',
            field=models.BooleanField(default=False, help_text='Is this period soft closed (prevents standard users but allows admins)?'),
        ),
        migrations.AddField(
            model_name='fiscalyear',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fiscal_years', to='institutions.institution'),
        ),
        migrations.AddField(
            model_name='generalledger',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='general_ledger_entries', to='institutions.institution'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='institutions.institution'),
        ),
        migrations.AlterField(
            model_name='financialperiod',
            name='is_closed',
            field=models.BooleanField(default=False, help_text='Is this period completely hard closed?'),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Department code', max_length=50)),
                ('name', models.CharField(help_text='Department name', max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('head_of_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='institutions.institution')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'db_table': 'finance_department',
                'unique_together': {('institution', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Campus code (e.g., MAIN, NORTH)', max_length=50)),
                ('name', models.CharField(help_text='Campus name', max_length=255)),
                ('is_headquarters', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campuses', to='institutions.institution')),
            ],
            options={
                'verbose_name': 'Campus',
                'verbose_name_plural': 'Campuses',
                'db_table': 'finance_campus',
                'unique_together': {('institution', 'code')},
            },
        ),
        migrations.AddField(
            model_name='generalledger',
            name='campus',
            field=models.ForeignKey(blank=True, help_text='Campus specific allocation', null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.campus'),
        ),
        migrations.AddField(
            model_name='generalledger',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Department specific allocation', null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.department'),
        ),
        migrations.AddField(
            model_name='journallineitem',
            name='campus',
            field=models.ForeignKey(blank=True, help_text='Campus specific allocation', null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.campus'),
        ),
        migrations.AddField(
            model_name='journallineitem',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Department specific allocation', null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.department'),
        ),
    ]
