# Generated by Django 4.2.29 on 2026-04-06 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_academicyear'),
        ('institutions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0002_account_institution_costcenter_institution_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='creditnote',
            name='finance_cre_credit__c59f9f_idx',
        ),
        migrations.RemoveIndex(
            model_name='creditnote',
            name='finance_cre_student_bb6cc0_idx',
        ),
        migrations.RemoveIndex(
            model_name='creditnote',
            name='finance_cre_invoice_517121_idx',
        ),
        migrations.RemoveIndex(
            model_name='feecategory',
            name='finance_fee_code_25140a_idx',
        ),
        migrations.RemoveIndex(
            model_name='feecategory',
            name='finance_fee_active_3f0702_idx',
        ),
        migrations.RemoveIndex(
            model_name='feetemplate',
            name='finance_fee_templat_8a1b3f_idx',
        ),
        migrations.RemoveIndex(
            model_name='feetemplate',
            name='finance_fee_academi_cc6834_idx',
        ),
        migrations.RemoveIndex(
            model_name='feetemplate',
            name='finance_fee_fee_cla_6610c0_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='finance_inv_invoice_89da8a_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='finance_inv_student_7ec268_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='finance_inv_status_d9b47e_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='finance_inv_issue_d_3b7e1d_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='finance_pay_payment_bb9d71_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='finance_pay_receipt_578993_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='finance_pay_student_14b4c3_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='finance_pay_payment_72f761_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='finance_pay_status_cb601d_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='finance_pay_allocat_5c9cf9_idx',
        ),
        migrations.RemoveIndex(
            model_name='receipt',
            name='finance_rec_receipt_e3529a_idx',
        ),
        migrations.RemoveIndex(
            model_name='receipt',
            name='finance_rec_payment_2725c0_idx',
        ),
        migrations.RemoveIndex(
            model_name='receipt',
            name='finance_rec_receipt_9193f8_idx',
        ),
        migrations.RemoveIndex(
            model_name='studentfinancialprofile',
            name='finance_stu_student_0f23f1_idx',
        ),
        migrations.RemoveIndex(
            model_name='studentfinancialprofile',
            name='finance_stu_current_bb513b_idx',
        ),
        migrations.RemoveIndex(
            model_name='studentfinancialprofile',
            name='finance_stu_financi_bf14b6_idx',
        ),
        migrations.RemoveIndex(
            model_name='studentfinancialprofile',
            name='finance_stu_arrears_1ff6e3_idx',
        ),
        migrations.AlterUniqueTogether(
            name='studentfinancialprofile',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='institution',
            field=models.ForeignKey(default=1, help_text='Institution issuing credit', on_delete=django.db.models.deletion.CASCADE, related_name='credit_notes', to='institutions.institution'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feecategory',
            name='institution',
            field=models.ForeignKey(default=1, help_text='Institution this fee category belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='fee_categories', to='institutions.institution'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feetemplate',
            name='institution',
            field=models.ForeignKey(default=1, help_text='Institution this fee template belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='fee_templates', to='institutions.institution'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='institution',
            field=models.ForeignKey(default=1, help_text='Institution this invoice belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='institutions.institution'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='institution',
            field=models.ForeignKey(default=1, help_text='Institution receiving the payment', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='institutions.institution'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentallocation',
            name='institution',
            field=models.ForeignKey(default=1, help_text='Institution context', on_delete=django.db.models.deletion.CASCADE, related_name='payment_allocations', to='institutions.institution'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receipt',
            name='institution',
            field=models.ForeignKey(default=1, help_text='Institution issuing receipt', on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='institutions.institution'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentfinancialprofile',
            name='institution',
            field=models.ForeignKey(default=1, help_text='Institution this profile operates under', on_delete=django.db.models.deletion.CASCADE, related_name='student_financial_profiles', to='institutions.institution'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='credit_note_number',
            field=models.CharField(db_index=True, help_text='Unique credit note number', max_length=50),
        ),
        migrations.AlterField(
            model_name='feecategory',
            name='code',
            field=models.CharField(db_index=True, help_text='Unique code for this fee category', max_length=50),
        ),
        migrations.AlterField(
            model_name='feetemplate',
            name='template_code',
            field=models.CharField(db_index=True, help_text='Unique code for this template', max_length=100),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(db_index=True, help_text='Unique invoice number (e.g., INV-2024-00001)', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_number',
            field=models.CharField(db_index=True, help_text='Unique payment number (e.g., PMT-2024-00001)', max_length=50),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='receipt_number',
            field=models.CharField(db_index=True, help_text='Receipt number', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentfinancialprofile',
            name='student',
            field=models.ForeignKey(help_text='Link to student user account (can exist in multiple institutions)', on_delete=django.db.models.deletion.PROTECT, related_name='financial_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='creditnote',
            unique_together={('institution', 'credit_note_number')},
        ),
        migrations.AlterUniqueTogether(
            name='feecategory',
            unique_together={('institution', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='feetemplate',
            unique_together={('institution', 'template_code')},
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('institution', 'invoice_number')},
        ),
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together={('institution', 'payment_number')},
        ),
        migrations.AlterUniqueTogether(
            name='receipt',
            unique_together={('institution', 'receipt_number')},
        ),
        migrations.AlterUniqueTogether(
            name='studentfinancialprofile',
            unique_together={('institution', 'student', 'academic_year')},
        ),
        migrations.AddIndex(
            model_name='creditnote',
            index=models.Index(fields=['institution', 'credit_note_number'], name='finance_cre_institu_313a8c_idx'),
        ),
        migrations.AddIndex(
            model_name='creditnote',
            index=models.Index(fields=['institution', 'student'], name='finance_cre_institu_bbbbbf_idx'),
        ),
        migrations.AddIndex(
            model_name='creditnote',
            index=models.Index(fields=['institution', 'invoice'], name='finance_cre_institu_e089b3_idx'),
        ),
        migrations.AddIndex(
            model_name='feecategory',
            index=models.Index(fields=['institution', 'code'], name='finance_fee_institu_250c38_idx'),
        ),
        migrations.AddIndex(
            model_name='feecategory',
            index=models.Index(fields=['institution', 'active'], name='finance_fee_institu_0d1a00_idx'),
        ),
        migrations.AddIndex(
            model_name='feetemplate',
            index=models.Index(fields=['institution', 'template_code'], name='finance_fee_institu_8b2c32_idx'),
        ),
        migrations.AddIndex(
            model_name='feetemplate',
            index=models.Index(fields=['institution', 'academic_year'], name='finance_fee_institu_df33f9_idx'),
        ),
        migrations.AddIndex(
            model_name='feetemplate',
            index=models.Index(fields=['institution', 'fee_class'], name='finance_fee_institu_d229fa_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['institution', 'invoice_number'], name='finance_inv_institu_68d005_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['institution', 'student'], name='finance_inv_institu_5358db_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['institution', 'status'], name='finance_inv_institu_d21528_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['institution', 'issue_date'], name='finance_inv_institu_882d31_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['institution', 'payment_number'], name='finance_pay_institu_3a002a_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['institution', 'receipt_number'], name='finance_pay_institu_a78c45_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['institution', 'student'], name='finance_pay_institu_bf343f_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['institution', 'payment_date'], name='finance_pay_institu_34ea71_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['institution', 'status'], name='finance_pay_institu_2b00b2_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['institution', 'allocation_status'], name='finance_pay_institu_3f318e_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['institution', 'receipt_number'], name='finance_rec_institu_0c81c9_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['institution', 'payment'], name='finance_rec_institu_5ba423_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['institution', 'receipt_date'], name='finance_rec_institu_2cd0b0_idx'),
        ),
        migrations.AddIndex(
            model_name='studentfinancialprofile',
            index=models.Index(fields=['institution', 'student'], name='finance_stu_institu_00ce61_idx'),
        ),
        migrations.AddIndex(
            model_name='studentfinancialprofile',
            index=models.Index(fields=['institution', 'current_class'], name='finance_stu_institu_4808d3_idx'),
        ),
        migrations.AddIndex(
            model_name='studentfinancialprofile',
            index=models.Index(fields=['institution', 'financial_status'], name='finance_stu_institu_d64889_idx'),
        ),
        migrations.AddIndex(
            model_name='studentfinancialprofile',
            index=models.Index(fields=['institution', 'arrears_balance'], name='finance_stu_institu_54022d_idx'),
        ),
    ]
