# Generated by Django 4.2.29 on 2026-04-23 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_grandfather_email_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='PilotFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_role', models.CharField(blank=True, default='', max_length=50)),
                ('severity', models.CharField(choices=[('bug', 'Bug / broken thing'), ('confusing', 'Confusing / unclear'), ('idea', 'Feature idea'), ('other', 'Other')], default='bug', max_length=20)),
                ('message', models.TextField()),
                ('page_url', models.CharField(blank=True, default='', max_length=500)),
                ('user_agent', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pilot feedback',
                'verbose_name_plural': 'Pilot feedback',
                'ordering': ['-created_at'],
            },
        ),
    ]
