# Generated by Django 6.0.4 on 2026-04-24 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_pilot_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stage',
            field=models.CharField(choices=[('primary', 'Primary (P4–P7)'), ('secondary', 'Secondary (S1–S6)')], default='secondary', help_text='Which platform this user sees. Set at registration; cannot mix.', max_length=10),
        ),
    ]
