# Generated by Django 6.0.4 on 2026-04-26 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyBuddyConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona', models.CharField(choices=[('student', 'Maple Study Buddy (student)'), ('parent', 'Maple Parent Guide'), ('teacher', 'Maple Teacher Assistant')], default='student', max_length=12)),
                ('title', models.CharField(blank=True, help_text='Short label derived from the first user message.', max_length=200)),
                ('subject', models.CharField(blank=True, max_length=64)),
                ('topic', models.CharField(blank=True, max_length=120)),
                ('escalated', models.BooleanField(default=False)),
                ('archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_buddy_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='StudyBuddyMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=12)),
                ('content', models.TextField()),
                ('escalation_hint', models.BooleanField(default=False)),
                ('model', models.CharField(blank=True, max_length=64)),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_services.studybuddyconversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='studybuddyconversation',
            index=models.Index(fields=['user', '-updated_at'], name='ai_services_user_id_287717_idx'),
        ),
        migrations.AddIndex(
            model_name='studybuddymessage',
            index=models.Index(fields=['conversation', 'created_at'], name='ai_services_convers_ea0642_idx'),
        ),
    ]
