# Generated by Django 4.2.29 on 2026-04-05 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='institution_logos/')),
                ('primary_color', models.CharField(default='#000000', max_length=7)),
                ('secondary_color', models.CharField(default='#ffffff', max_length=7)),
                ('country_code', models.CharField(default='uganda', max_length=10)),
                ('curriculum_track', models.CharField(default='national', max_length=100)),
                ('subscription_plan', models.CharField(default='free', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TemporaryPinReset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('sms', 'Parent SMS'), ('admin', 'School Admin')], max_length=20)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_resets', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pin_resets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherQualityScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consistency_score', models.IntegerField(default=0, help_text='0-100 score based on lesson delivery timing')),
                ('curriculum_fidelity_score', models.IntegerField(default=0, help_text='0-100 score based on topic competency tagging')),
                ('is_ncdc_verified', models.BooleanField(default=False, help_text='Has the teacher been verified by external moderation bodies?')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_scores', to='institutions.institution')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quality_score', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_tier', models.CharField(default='free', max_length=50)),
                ('monthly_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('currency', models.CharField(default='UGX', max_length=10)),
                ('next_billing_date', models.DateField(blank=True, null=True)),
                ('is_suspended', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ledger', to='institutions.institution')),
            ],
        ),
        migrations.CreateModel(
            name='LearnerRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('learner_id_number', models.CharField(blank=True, max_length=100, null=True)),
                ('parent_name', models.CharField(blank=True, max_length=255, null=True)),
                ('parent_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('parent_relationship', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_payment', 'Pending Payment'), ('payment_verified', 'Payment Verified'), ('account_creation_pending', 'Account Creation Pending'), ('active', 'Active'), ('failed', 'Failed')], default='draft', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='curriculum.classlevel')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learner_registrations', to='institutions.institution')),
                ('student_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_record', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionImplementationScorecard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syllabus_coverage_pct', models.DecimalField(decimal_places=2, default=0.0, help_text='e.g. 85.50%', max_digits=5)),
                ('assessment_compliance_score', models.DecimalField(decimal_places=2, default=0.0, help_text='Measures formative/summative alignment', max_digits=5)),
                ('practical_learning_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('last_computed', models.DateTimeField(auto_now=True)),
                ('institution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_scorecard', to='institutions.institution')),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_offered', models.BooleanField(default=True)),
                ('custom_name', models.CharField(blank=True, help_text='Optional local override for the global subject name', max_length=200, null=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_subjects', to='institutions.institution')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_in_institutions', to='curriculum.subject')),
            ],
            options={
                'unique_together': {('institution', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='InstitutionMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('headteacher', 'Headteacher'), ('deputy', 'Deputy Headteacher'), ('bursar', 'Bursar / Finance'), ('registrar', 'Registrar / Admissions'), ('dos', 'Director of Studies'), ('class_teacher', 'Class Teacher'), ('subject_teacher', 'Subject Teacher'), ('librarian', 'Librarian'), ('counselor', 'Counselor'), ('exam_officer', 'Exam Officer'), ('ict_admin', 'ICT Administrator'), ('parent', 'Parent / Guardian'), ('student', 'Student')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='institutions.institution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institution_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'institution', 'role')},
            },
        ),
    ]
