# Generated by Django 4.2.29 on 2026-04-08 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubscriptionLedger',
        ),
    ]
