# Generated by Django 4.2.29 on 2026-04-02 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
        ('institutions', '0002_alter_institutionmembership_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_offered', models.BooleanField(default=True)),
                ('custom_name', models.CharField(blank=True, help_text='Optional local override for the global subject name', max_length=200, null=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_subjects', to='institutions.institution')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_in_institutions', to='curriculum.subject')),
            ],
            options={
                'unique_together': {('institution', 'subject')},
            },
        ),
    ]
