# Generated by Django 4.2.29 on 2026-04-08 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_delete_subscriptionledger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutionmembership',
            name='role',
            field=models.CharField(choices=[('headteacher', 'Headteacher'), ('deputy', 'Deputy Headteacher'), ('registrar', 'Registrar / Admissions'), ('dos', 'Director of Studies'), ('class_teacher', 'Class Teacher'), ('subject_teacher', 'Subject Teacher'), ('librarian', 'Librarian'), ('counselor', 'Counselor'), ('exam_officer', 'Exam Officer'), ('ict_admin', 'ICT Administrator'), ('parent', 'Parent / Guardian'), ('student', 'Student')], max_length=20),
        ),
    ]
