# Generated by Django 4.2.29 on 2026-04-08 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0003_alter_institutionmembership_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='grade_offerings',
            field=models.JSONField(default=list, help_text='List of internal_canonical_grades this institution offers e.g. [4, 5, 6, 7] for Primary'),
        ),
        migrations.AddField(
            model_name='institution',
            name='school_level',
            field=models.CharField(choices=[('primary', 'Primary School'), ('secondary', 'Secondary School'), ('mixed', 'Mixed (Primary & Secondary)')], default='secondary', max_length=20),
        ),
    ]
