# Generated by Django 4.2.29 on 2026-04-02 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('institutions', '0003_institutionsubject'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherQualityScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consistency_score', models.IntegerField(default=0, help_text='0-100 score based on lesson delivery timing')),
                ('curriculum_fidelity_score', models.IntegerField(default=0, help_text='0-100 score based on topic competency tagging')),
                ('is_ncdc_verified', models.BooleanField(default=False, help_text='Has the teacher been verified by external moderation bodies?')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_scores', to='institutions.institution')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quality_score', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_tier', models.CharField(default='free', max_length=50)),
                ('monthly_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('currency', models.CharField(default='UGX', max_length=10)),
                ('next_billing_date', models.DateField(blank=True, null=True)),
                ('is_suspended', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ledger', to='institutions.institution')),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionImplementationScorecard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syllabus_coverage_pct', models.DecimalField(decimal_places=2, default=0.0, help_text='e.g. 85.50%', max_digits=5)),
                ('assessment_compliance_score', models.DecimalField(decimal_places=2, default=0.0, help_text='Measures formative/summative alignment', max_digits=5)),
                ('practical_learning_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('last_computed', models.DateTimeField(auto_now=True)),
                ('institution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_scorecard', to='institutions.institution')),
            ],
        ),
    ]
