# Generated by Django 4.2.29 on 2026-04-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0004_institution_grade_offerings_institution_school_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='school_level',
            field=models.CharField(choices=[('primary', 'Primary School'), ('secondary', 'Secondary School')], default='secondary', max_length=20),
        ),
    ]
