# Generated by Django 4.2.29 on 2026-04-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0005_alter_institution_school_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='in_grace_period',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='institution',
            name='tier_expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
