# Generated by Django 4.2.29 on 2026-04-14 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('institutions', '0006_institution_in_grace_period_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('price_ugx', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('duration_days', models.IntegerField(default=30, help_text='Number of days the subscription is valid for')),
                ('access_scope', models.CharField(default='full', help_text='e.g. full, basic, premium', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='learnerregistration',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learnerregistration',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='learnerregistration',
            name='parent_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learnerregistration',
            name='parent_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='learnerregistration',
            name='parent_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='learnerregistration',
            name='parent_phone_secondary',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='learnerregistration',
            name='parent_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_registrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='learnerregistration',
            name='payer_phone',
            field=models.CharField(blank=True, help_text='Phone number authorizing payment', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='learnerregistration',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('mtn_momo', 'MTN Mobile Money'), ('airtel_money', 'Airtel Money'), ('visa_pesapal', 'Visa Card (Pesapal)')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='learnerregistration',
            name='stream_section',
            field=models.CharField(blank=True, help_text="Stream or section e.g. 'East', 'A'", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='learnerregistration',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('parent_linked', 'Parent Linked'), ('subscription_selected', 'Subscription Selected'), ('payment_pending', 'Payment Pending'), ('payment_in_progress', 'Payment In Progress'), ('payment_failed', 'Payment Failed'), ('payment_success', 'Payment Successful'), ('activated', 'Activated')], default='draft', max_length=30),
        ),
        migrations.CreateModel(
            name='StudentPaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=255)),
                ('parent_name', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='UGX', max_length=10)),
                ('payment_method', models.CharField(choices=[('mtn_momo', 'MTN Mobile Money'), ('airtel_money', 'Airtel Money'), ('visa_pesapal', 'Visa Card (Pesapal)')], max_length=20)),
                ('payer_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('provider_reference', models.CharField(blank=True, help_text='External reference from payment provider', max_length=255, null=True)),
                ('internal_reference', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('pending', 'Pending'), ('awaiting_authorization', 'Awaiting Authorization'), ('successful', 'Successful'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='initiated', max_length=30)),
                ('provider_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='institutions.institution')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_attempts', to='institutions.learnerregistration')),
                ('subscription_plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='institutions.subscriptionplan')),
            ],
        ),
        migrations.CreateModel(
            name='StudentActivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('locked', 'Locked'), ('pending_payment', 'Pending Payment'), ('active', 'Active'), ('suspended', 'Suspended'), ('expired', 'Expired')], default='locked', max_length=20)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institutions.learnerregistration')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='activation', to=settings.AUTH_USER_MODEL)),
                ('subscription_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institutions.subscriptionplan')),
            ],
        ),
        migrations.AddField(
            model_name='learnerregistration',
            name='subscription_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institutions.subscriptionplan'),
        ),
    ]
