# Generated by Django 4.2.29 on 2026-04-05 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_link', models.URLField(max_length=500)),
                ('replay_url', models.URLField(blank=True, max_length=500, null=True)),
                ('provider', models.CharField(choices=[('google_meet', 'Google Meet'), ('zoom', 'Zoom')], default='google_meet', max_length=50)),
                ('provider_event_id', models.CharField(blank=True, max_length=255, null=True)),
                ('scheduled_start', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(default=60)),
                ('capacity', models.IntegerField(default=100)),
                ('enrolled_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('artifact_sync_status', models.CharField(choices=[('none', 'Not Required'), ('pending', 'Pending Sync'), ('syncing', 'Syncing to Pipeline'), ('completed', 'Replay Available'), ('failed', 'Pipeline Failed')], default='none', max_length=20)),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='live_session', to='lessons.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='SessionReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='live_sessions.livesession')),
            ],
        ),
    ]
