# Generated by Django 4.2.29 on 2026-04-02 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesession',
            name='capacity',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='livesession',
            name='duration_minutes',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='livesession',
            name='enrolled_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='livesession',
            name='scheduled_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
