# Generated by Django 4.2.29 on 2026-04-11 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('live_sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissedSessionRecovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True, default='')),
                ('recording_url', models.URLField(blank=True, max_length=500, null=True)),
                ('recovery_status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('verified', 'Verified')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_records', to='live_sessions.livesession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missed_session_recoveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Missed Session Recoveries',
                'unique_together': {('session', 'student')},
            },
        ),
        migrations.CreateModel(
            name='RecoveryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file_type', models.CharField(default='PDF', max_length=50)),
                ('file_url', models.URLField(blank=True, max_length=500, null=True)),
                ('recovery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='live_sessions.missedsessionrecovery')),
            ],
        ),
    ]
