# Generated by Django 6.0.4 on 2026-04-24 04:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerPathway',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('recommended_subjects', models.JSONField(blank=True, default=list)),
                ('required_skills', models.JSONField(blank=True, default=list, help_text='Soft + hard skills this pathway tends to use.')),
                ('typical_roles', models.JSONField(blank=True, default=list)),
                ('education_levels', models.JSONField(blank=True, default=list, help_text='Typical qualifications — diploma, BSc, etc.')),
                ('related_industries', models.JSONField(blank=True, default=list)),
                ('icon_emoji', models.CharField(blank=True, default='🧭', max_length=8)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='PathwaySuggestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('confidence', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('reasoning', models.TextField(blank=True, help_text='Parent/student-friendly explanation.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pathway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='pathways.careerpathway')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pathway_suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-confidence', '-created_at'],
                'unique_together': {('student', 'pathway')},
            },
        ),
    ]
