# Generated by Django 6.0.4 on 2026-04-24 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathways', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerpathway',
            name='stage',
            field=models.CharField(choices=[('primary', 'Primary (P4–P7)'), ('secondary', 'Secondary (S1–S6)'), ('both', 'Both stages')], default='secondary', max_length=10),
        ),
    ]
