# Generated by Django 4.2.29 on 2026-04-05 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content_type', models.CharField(choices=[('video', 'Video Lesson'), ('notes', 'Revision Notes'), ('assessment', 'Practice Test')], default='video', max_length=20)),
                ('price_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='[DEPRECATED] Use billing.SubjectClassProduct for public pricing.', max_digits=10, null=True)),
                ('currency', models.CharField(default='UGX', max_length=10)),
                ('visibility_state', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('average_rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=3)),
                ('review_count', models.IntegerField(default=0)),
                ('student_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PayoutRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('net_payable', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status', models.CharField(choices=[('available', 'Available'), ('requested', 'Requested'), ('queued', 'Queued'), ('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Failed'), ('reversed', 'Reversed'), ('cancelled', 'Cancelled')], default='requested', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payout_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherPayoutProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(help_text='Mobile Money number used for disbursement', max_length=20)),
                ('network', models.CharField(choices=[('mtn', 'MTN Uganda'), ('airtel', 'Airtel Uganda')], default='mtn', max_length=50)),
                ('account_name', models.CharField(blank=True, max_length=255)),
                ('is_verified', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payout_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherPayoutBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cycle_start_date', models.DateTimeField()),
                ('cycle_end_date', models.DateTimeField()),
                ('gross_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('deduction_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('net_payout', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status', models.CharField(choices=[('calculated', 'Calculated'), ('pending_disbursement', 'Pending Disbursement'), ('disbursed', 'Disbursed'), ('failed', 'Failed')], default='calculated', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('disbursed_at', models.DateTimeField(blank=True, null=True)),
                ('payout_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='marketplace.payoutrequest')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_batches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PayoutTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('source_wallet', models.CharField(default='CONFIGURED_IN_ENV', max_length=50)),
                ('destination_number', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('created', 'Created'), ('submitted_to_provider', 'Submitted to Provider'), ('provider_pending', 'Provider Pending'), ('provider_success', 'Provider Success'), ('provider_failed', 'Provider Failed'), ('reconciliation_pending', 'Reconciliation Pending'), ('reconciled', 'Reconciled')], default='created', max_length=50)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payout_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='marketplace.payoutrequest')),
            ],
        ),
        migrations.CreateModel(
            name='PayoutAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=100)),
                ('old_status', models.CharField(blank=True, max_length=50, null=True)),
                ('new_status', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('payout_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='marketplace.payoutrequest')),
            ],
        ),
        migrations.CreateModel(
            name='LicenseDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_granted_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='marketplace.listing')),
                ('purchaser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_licenses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ListingTopicBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_bindings', to='marketplace.listing')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='curriculum.topic')),
            ],
            options={
                'unique_together': {('listing', 'topic')},
            },
        ),
    ]
