# Generated by Django 4.2.29 on 2026-04-02 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='average_rating',
            field=models.DecimalField(decimal_places=1, default=5.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='listing',
            name='content_type',
            field=models.CharField(choices=[('video', 'Video Lesson'), ('notes', 'Revision Notes'), ('assessment', 'Practice Test')], default='video', max_length=20),
        ),
        migrations.AddField(
            model_name='listing',
            name='review_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='student_count',
            field=models.IntegerField(default=0),
        ),
    ]
