# Generated by Django 6.0.4 on 2026-04-24 04:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0004_classlevel_internal_canonical_grade_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=280, unique=True)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('exam_track', models.CharField(blank=True, choices=[('', 'None'), ('PLE', 'PLE'), ('UCE', 'UCE'), ('UACE', 'UACE'), ('KCSE', 'KCSE'), ('general', 'General')], default='', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('weekly_plan', models.JSONField(blank=True, default=list)),
                ('max_seats', models.PositiveIntegerField(default=0, help_text='0 = unlimited')),
                ('is_premium', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('cover_image', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='curriculum.classlevel')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='curriculum.subject')),
                ('teacher_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_cohorts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='CohortEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('dropped', 'Dropped')], default='active', max_length=20)),
                ('progress_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='cohorts.cohort')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohort_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-enrolled_at'],
                'unique_together': {('cohort', 'student')},
            },
        ),
    ]
