# Generated by Django 6.0.4 on 2026-04-24 04:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('low_data_mode', models.BooleanField(default=False, help_text='Serve lower-res images, skip autoplay, prefer audio lessons.')),
                ('prefer_audio_lessons', models.BooleanField(default=False)),
                ('allow_offline_downloads', models.BooleanField(default=True, help_text='Allow cached lesson notes for offline reading.')),
                ('whatsapp_optin', models.BooleanField(default=False)),
                ('sms_optin', models.BooleanField(default=False)),
                ('weekly_brief_delivery', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS')], default='email', max_length=20)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learner_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
