import React, { useState, useEffect } from 'react';
import { useAuth } from '../contexts/AuthContext';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '../components/ui/card';
import { Button } from '../components/ui/button';
import { Badge } from '../components/ui/badge';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '../components/ui/tabs';
import { Input } from '../components/ui/input';
import { Textarea } from '../components/ui/textarea';
import { apiClient } from '../lib/api';
import {
  LineChart, Line, AreaChart, Area, BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip as RechartsTooltip, ResponsiveContainer, Legend
} from 'recharts';
import {
  Brain,
  AlertTriangle,
  TrendingUp,
  MessageSquare,
  Zap,
  Clock,
  Users,
  CheckCircle,
  BookOpen,
  BarChart3,
  Lightbulb,
  Copy,
  RefreshCw,
} from 'lucide-react';

interface AutoGeneratedQuiz {
  id: string;
  topic: string;
  questions: any[];
}

const mockChartData = [
  { name: 'Mon', engagement: 45, completion: 80, helpRequests: 5 },
  { name: 'Tue', engagement: 52, completion: 85, helpRequests: 3 },
  { name: 'Wed', engagement: 48, completion: 82, helpRequests: 6 },
  { name: 'Thu', engagement: 61, completion: 89, helpRequests: 2 },
  { name: 'Fri', engagement: 55, completion: 88, helpRequests: 4 },
  { name: 'Sat', engagement: 30, completion: 60, helpRequests: 1 },
  { name: 'Sun', engagement: 42, completion: 75, helpRequests: 2 },
];

export const AITeachingAssistant: React.FC = () => {
  const { user } = useAuth();
  const [selectedQuestion, setSelectedQuestion] = useState<string>('');
  const [generatedReply, setGeneratedReply] = useState<string>('');
  const [replyLoading, setReplyLoading] = useState(false);
  
  const [quizTopic, setQuizTopic] = useState<string>('');
  const [autoQuizzes, setAutoQuizzes] = useState<AutoGeneratedQuiz[]>([]);
  const [quizLoading, setQuizLoading] = useState(false);

  const [analyticsReport, setAnalyticsReport] = useState<string>('');
  const [analyticsLoading, setAnalyticsLoading] = useState(false);

  useEffect(() => {
    // Generate AI Analytics Report on initial load
    fetchAnalyticsReport();
  }, []);

  const fetchAnalyticsReport = async () => {
    setAnalyticsLoading(true);
    try {
      const res = await apiClient.post('/ai/copilot/ask/', {
        content: "Draft weekly analytics summary.",
        context: "teaching_analytics"
      });
      setAnalyticsReport(res.data.reply);
    } catch (err) {
      console.error(err);
      setAnalyticsReport("Failed to generate analytics report via OpenAI.");
    } finally {
      setAnalyticsLoading(false);
    }
  };

  const generateSmartReply = async () => {
    if (!selectedQuestion) return;
    setReplyLoading(true);
    try {
      const res = await apiClient.post('/ai/copilot/ask/', {
        content: selectedQuestion,
        context: "smart_reply"
      });
      setGeneratedReply(res.data.reply);
    } catch (err) {
      setGeneratedReply("Sorry, there was an issue connecting to the AI service.");
    } finally {
      setReplyLoading(false);
    }
  };

  const generateQuiz = async () => {
    if (!quizTopic) return;
    setQuizLoading(true);
    try {
      const res = await apiClient.post('/ai/copilot/ask/', {
        content: quizTopic,
        context: "quiz_generator"
      });
      
      const parsedQuiz = typeof res.data.reply === 'string' ? JSON.parse(res.data.reply) : res.data.reply;
      
      const newQuiz: AutoGeneratedQuiz = {
        id: `quiz-${Date.now()}`,
        topic: quizTopic,
        questions: parsedQuiz.questions || []
      };
      
      setAutoQuizzes(prev => [newQuiz, ...prev]);
      setQuizTopic('');
    } catch (err) {
      console.error("AI Quiz failed:", err);
    } finally {
      setQuizLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-gray-50">
      <div className="bg-white border-b shadow-sm">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-6 flex justify-between items-center">
          <div>
            <div className="flex items-center gap-2 mb-2">
              <Brain className="h-6 w-6 text-indigo-600" />
              <span className="text-indigo-600 font-semibold tracking-wide">Edify Copilot OS</span>
            </div>
            <h1 className="text-3xl font-bold text-gray-900">Deep Analytics & AI Interventions</h1>
            <p className="text-gray-600 mt-1">
              Leverage live OpenAI inferences over your real classroom metrics to rapidly build and intervene.
            </p>
          </div>
        </div>
      </div>

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <Tabs defaultValue="analytics" className="space-y-6">
          <TabsList className="grid w-full grid-cols-4 lg:w-[600px] bg-white border border-gray-200">
            <TabsTrigger value="analytics" className="data-[state=active]:bg-indigo-50 data-[state=active]:text-indigo-700">
              <BarChart3 className="h-4 w-4 mr-2" />
              Live Analytics
            </TabsTrigger>
            <TabsTrigger value="smart-replies" className="data-[state=active]:bg-indigo-50 data-[state=active]:text-indigo-700">
              <MessageSquare className="h-4 w-4 mr-2" />
              Smart Replies
            </TabsTrigger>
            <TabsTrigger value="quiz-generator" className="data-[state=active]:bg-indigo-50 data-[state=active]:text-indigo-700">
              <Zap className="h-4 w-4 mr-2" />
              Quiz Generator
            </TabsTrigger>
          </TabsList>

          <TabsContent value="analytics" className="space-y-6">
            <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
              <Card>
                <CardHeader className="pb-2">
                  <CardTitle className="text-sm font-medium text-gray-500 flex items-center gap-2">
                    <Users className="h-4 w-4 text-blue-500" /> Engagement
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="text-3xl font-bold text-gray-900">45m</div>
                  <p className="text-xs text-green-600 font-medium">↑ 12% from last week</p>
                </CardContent>
              </Card>
              <Card>
                <CardHeader className="pb-2">
                  <CardTitle className="text-sm font-medium text-gray-500 flex items-center gap-2">
                    <CheckCircle className="h-4 w-4 text-green-500" /> Completion Rate
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="text-3xl font-bold text-gray-900">87%</div>
                  <p className="text-xs text-green-600 font-medium">↑ 5% from last week</p>
                </CardContent>
              </Card>
              <Card>
                <CardHeader className="pb-2">
                  <CardTitle className="text-sm font-medium text-gray-500 flex items-center gap-2">
                    <AlertTriangle className="h-4 w-4 text-orange-500" /> Help Requests
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="text-3xl font-bold text-gray-900">23</div>
                  <p className="text-xs text-red-600 font-medium">Spike detected in Math</p>
                </CardContent>
              </Card>
              <Card>
                 <CardHeader className="pb-2">
                  <CardTitle className="text-sm font-medium text-gray-500 flex items-center gap-2">
                    <TrendingUp className="h-4 w-4 text-purple-500" /> Projected Success
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="text-3xl font-bold text-gray-900">92%</div>
                  <p className="text-xs text-gray-500">Based on grading curve</p>
                </CardContent>
              </Card>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
              {/* Massive Analytics Visualization */}
              <Card className="lg:col-span-2">
                <CardHeader>
                  <CardTitle>Classroom Engagement Trajectory</CardTitle>
                  <CardDescription>Average active minutes mapped against assignment completion rates over the last 7 days.</CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="h-80 w-full">
                    <ResponsiveContainer width="100%" height="100%">
                      <AreaChart data={mockChartData} margin={{ top: 10, right: 30, left: 0, bottom: 0 }}>
                        <defs>
                          <linearGradient id="colorEngagement" x1="0" y1="0" x2="0" y2="1">
                            <stop offset="5%" stopColor="#4f46e5" stopOpacity={0.3}/>
                            <stop offset="95%" stopColor="#4f46e5" stopOpacity={0}/>
                          </linearGradient>
                          <linearGradient id="colorCompletion" x1="0" y1="0" x2="0" y2="1">
                            <stop offset="5%" stopColor="#10b981" stopOpacity={0.3}/>
                            <stop offset="95%" stopColor="#10b981" stopOpacity={0}/>
                          </linearGradient>
                        </defs>
                        <XAxis dataKey="name" stroke="#9ca3af" />
                        <YAxis stroke="#9ca3af" />
                        <CartesianGrid strokeDasharray="3 3" vertical={false} />
                        <RechartsTooltip 
                           contentStyle={{ borderRadius: '8px', border: 'none', boxShadow: '0 4px 6px -1px rgb(0 0 0 / 0.1)' }}
                        />
                        <Area type="monotone" dataKey="engagement" stroke="#4f46e5" strokeWidth={3} fillOpacity={1} fill="url(#colorEngagement)" name="Active Logins (min)" />
                        <Area type="monotone" dataKey="completion" stroke="#10b981" strokeWidth={3} fillOpacity={1} fill="url(#colorCompletion)" name="Task Completion (%)" />
                      </AreaChart>
                    </ResponsiveContainer>
                  </div>
                </CardContent>
              </Card>

              {/* AI Deep Insights Pane */}
              <Card className="border-indigo-100 bg-indigo-50/50">
                <CardHeader>
                  <CardTitle className="flex items-center gap-2 text-indigo-900">
                    <Lightbulb className="h-5 w-5 text-indigo-600" />
                    AI Copilot Analysis
                  </CardTitle>
                  <CardDescription>Live inferences based on your dataset.</CardDescription>
                </CardHeader>
                <CardContent>
                  {analyticsLoading ? (
                    <div className="flex items-center justify-center h-48">
                      <RefreshCw className="h-6 w-6 text-indigo-400 animate-spin" />
                    </div>
                  ) : (
                    <div className="prose prose-sm prose-indigo whitespace-pre-wrap text-gray-800">
                      {analyticsReport || "No report available."}
                    </div>
                  )}
                  <Button 
                    variant="outline" 
                    size="sm" 
                    className="w-full mt-4 border-indigo-200 text-indigo-700 bg-white hover:bg-indigo-50"
                    onClick={fetchAnalyticsReport}
                    disabled={analyticsLoading}
                  >
                    Refresh Insights
                  </Button>
                </CardContent>
              </Card>
            </div>
          </TabsContent>

          <TabsContent value="smart-replies">
            <Card className="max-w-3xl">
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <MessageSquare className="h-5 w-5 text-blue-500" />
                  Live Smart Reply Generator
                </CardTitle>
                <CardDescription>Paste a confused student's question and receive a structured, pedagogical response to help guide them instantly.</CardDescription>
              </CardHeader>
              <CardContent>
                <div className="space-y-4">
                  <div>
                    <Textarea
                      placeholder="e.g. Sir, why do we use the quadratic formula instead of completing the square?"
                      value={selectedQuestion}
                      onChange={(e) => setSelectedQuestion(e.target.value)}
                      rows={4}
                      className="resize-none"
                    />
                  </div>
                  
                  <Button onClick={generateSmartReply} disabled={!selectedQuestion || replyLoading} className="w-full sm:w-auto bg-blue-600 hover:bg-blue-700">
                    {replyLoading ? <RefreshCw className="mr-2 h-4 w-4 animate-spin" /> : <Zap className="mr-2 h-4 w-4" />}
                    {replyLoading ? "Generating Pedagogical Output..." : "Generate Smart Reply"}
                  </Button>
                  
                  {generatedReply && (
                    <div className="mt-6 border border-blue-100 rounded-xl p-5 bg-gradient-to-r from-blue-50 to-white shadow-sm">
                      <div className="flex items-center justify-between mb-3 border-b border-blue-100 pb-2">
                        <h4 className="font-semibold text-blue-900 flex items-center gap-2">
                           <Brain className="h-4 w-4"/> AI-Crafted Response
                        </h4>
                        <Button size="icon" variant="ghost" className="text-blue-600 hover:text-blue-800 hover:bg-blue-100 h-8 w-8" onClick={() => navigator.clipboard.writeText(generatedReply)}>
                          <Copy className="h-4 w-4" />
                        </Button>
                      </div>
                      <p className="text-sm text-gray-800 leading-relaxed whitespace-pre-wrap">{generatedReply}</p>
                    </div>
                  )}
                </div>
              </CardContent>
            </Card>
          </TabsContent>

          <TabsContent value="quiz-generator">
            <Card className="max-w-4xl">
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <Zap className="h-5 w-5 text-green-500" />
                  Structured Quiz AI Generator
                </CardTitle>
                <CardDescription>Tell the Copilot a curriculum topic. It will execute an LLM prompt that strictly formats Output JSON into our database schemas for immediate previewing.</CardDescription>
              </CardHeader>
              <CardContent>
                <div className="space-y-6">
                  <div className="flex flex-col sm:flex-row gap-4">
                    <Input
                      placeholder="e.g. Advanced Cellular Respiration"
                      value={quizTopic}
                      onChange={(e) => setQuizTopic(e.target.value)}
                      className="flex-1"
                    />
                    <Button onClick={generateQuiz} disabled={!quizTopic || quizLoading} className="bg-green-600 hover:bg-green-700 whitespace-nowrap">
                      {quizLoading ? <RefreshCw className="mr-2 h-4 w-4 animate-spin" /> : <Zap className="mr-2 h-4 w-4" />}
                      Generate JSON Quiz
                    </Button>
                  </div>

                  <div className="space-y-4">
                    {autoQuizzes.map((quiz, i) => (
                      <Card key={i} className="border border-green-200 shadow-sm overflow-hidden">
                         <div className="bg-green-50 px-4 py-3 border-b border-green-200 flex justify-between items-center">
                            <span className="font-bold text-green-800">Topic: {quiz.topic}</span>
                            <Badge variant="outline" className="bg-white text-green-700 border-green-300">Ready to Deploy</Badge>
                         </div>
                         <div className="p-4 space-y-5">
                            {quiz.questions?.map((q, qIndex) => (
                               <div key={q.id} className="border rounded p-4">
                                  <h4 className="font-semibold text-gray-800 mb-3">{qIndex + 1}. {q.question}</h4>
                                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 mb-3">
                                     {q.options?.map((opt: string, optIndex: number) => (
                                        <div key={optIndex} className={`p-2 text-sm rounded border ${opt === q.correctAnswer ? 'bg-green-100 border-green-400 font-medium text-green-900' : 'bg-gray-50 border-gray-200 text-gray-700'}`}>
                                            {opt}
                                            {opt === q.correctAnswer && <CheckCircle className="inline ml-2 h-4 w-4 text-green-600" />}
                                        </div>
                                     ))}
                                  </div>
                                  <div className="text-xs bg-indigo-50 text-indigo-800 p-2 rounded flex items-start gap-2">
                                     <Brain className="h-4 w-4 flex-shrink-0 mt-0.5" />
                                     <span><strong>AI Explanation:</strong> {q.explanation}</span>
                                  </div>
                               </div>
                            ))}
                         </div>
                      </Card>
                    ))}
                  </div>

                </div>
              </CardContent>
            </Card>
          </TabsContent>
        </Tabs>
      </div>
    </div>
  );
};

export default AITeachingAssistant;
