import React, { useState, useEffect } from 'react';
import { useAuth } from '../contexts/AuthContext';
import { Card, CardContent, CardHeader, CardTitle } from '../components/ui/card';
import { Button } from '../components/ui/button';
import { Badge } from '../components/ui/badge';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '../components/ui/tabs';
import { Input } from '../components/ui/input';
import { Textarea } from '../components/ui/textarea';
import {
  Brain,
  AlertTriangle,
  TrendingUp,
  MessageSquare,
  Zap,
  Clock,
  Users,
  CheckCircle,
  BookOpen,
  BarChart3,
  Lightbulb,
  Target,
  Star,
  MapPin,
  HelpCircle,
  Send,
  Copy,
  Download,
  RefreshCw,
  Eye,
  ThumbsUp
} from 'lucide-react';
import { ConfusionReport, SmartReply, AutoGeneratedQuiz } from '../types';

export const AITeachingAssistant: React.FC = () => {
  const { user } = useAuth();
  const [confusionReport, setConfusionReport] = useState<ConfusionReport | null>(null);
  const [smartReplies, setSmartReplies] = useState<SmartReply[]>([]);
  const [autoQuizzes, setAutoQuizzes] = useState<AutoGeneratedQuiz[]>([]);
  const [teachingAnalytics, setTeachingAnalytics] = useState<any>(null);
  const [selectedQuestion, setSelectedQuestion] = useState<string>('');
  const [generatedReply, setGeneratedReply] = useState<string>('');
  const [quizTopic, setQuizTopic] = useState<string>('');
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchAIData = async () => {
      try {
        const response = await fetch('/data/ai-assistant.json');
        const data = await response.json();
        
        setConfusionReport(data.confusionReports['weekly-2025-w27']);
        setSmartReplies(data.smartReplies.commonQuestions);
        setAutoQuizzes(data.autoQuizGenerator.generatedQuizzes);
        if (user?.id && data.teachingAnalytics[user.id]) {
          setTeachingAnalytics(data.teachingAnalytics[user.id]);
        } else {
          // Use sample data for demo
          setTeachingAnalytics(data.teachingAnalytics['sarah-nakamya']);
        }
      } catch (error) {
        console.error('Error fetching AI assistant data:', error);
      } finally {
        setLoading(false);
      }
    };

    fetchAIData();
  }, [user]);

  const generateSmartReply = () => {
    if (!selectedQuestion) return;
    
    const matchingReply = smartReplies.find(reply => 
      reply.question.toLowerCase().includes(selectedQuestion.toLowerCase()) ||
      selectedQuestion.toLowerCase().includes(reply.question.toLowerCase())
    );
    
    if (matchingReply) {
      setGeneratedReply(matchingReply.suggestedReply);
    } else {
      setGeneratedReply("I'd be happy to help you with this question! Let me break this down step by step and provide you with a clear explanation. Based on our curriculum, here's what you need to know...");
    }
  };

  const generateQuiz = () => {
    if (!quizTopic) return;
    
    // Simulate quiz generation
    const newQuiz: AutoGeneratedQuiz = {
      id: `quiz-${Date.now()}`,
      subject: 'Mathematics',
      topic: quizTopic,
      class: 'Senior 2',
      generatedDate: new Date().toISOString().split('T')[0],
      difficulty: 'medium',
      estimatedMinutes: 15,
      questions: [
        {
          id: 'q1',
          type: 'multiple-choice',
          question: `What is a key concept in ${quizTopic}?`,
          options: ['Option A', 'Option B', 'Option C', 'Option D'],
          correctAnswer: 'Option A',
          explanation: `This demonstrates the fundamental principle of ${quizTopic}.`,
          sourceContent: 'Generated from curriculum analysis'
        }
      ],
      deploymentStatus: 'ready',
      targetStudents: ['senior-2-students']
    };
    
    setAutoQuizzes(prev => [newQuiz, ...prev]);
    setQuizTopic('');
  };

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <div className="text-center">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600 mx-auto mb-4"></div>
          <p className="text-gray-600">Loading AI Teaching Assistant...</p>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gray-50">
      <div className="bg-white border-b">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-6">
          <div className="flex items-center gap-2 mb-4">
            <MapPin className="h-5 w-5 text-blue-600" />
            <span className="text-blue-600 font-medium">AI-Powered Teaching for Uganda</span>
          </div>
          <h1 className="text-3xl font-bold text-gray-900 mb-4">AI Teaching Assistant</h1>
          <p className="text-lg text-gray-600">
            Intelligent insights and automated tools to enhance your teaching effectiveness
          </p>
        </div>
      </div>

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <Tabs defaultValue="overview" className="space-y-6">
          <TabsList className="grid w-full grid-cols-4">
            <TabsTrigger value="overview" className="flex items-center gap-2">
              <Brain className="h-4 w-4" />
              Overview
            </TabsTrigger>
            <TabsTrigger value="smart-replies" className="flex items-center gap-2">
              <MessageSquare className="h-4 w-4" />
              Smart Replies
            </TabsTrigger>
            <TabsTrigger value="quiz-generator" className="flex items-center gap-2">
              <Zap className="h-4 w-4" />
              Quiz Generator
            </TabsTrigger>
            <TabsTrigger value="analytics" className="flex items-center gap-2">
              <BarChart3 className="h-4 w-4" />
              Analytics
            </TabsTrigger>
          </TabsList>

          <TabsContent value="overview">
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
              <Card>
                <CardHeader>
                  <CardTitle className="flex items-center gap-2">
                    <AlertTriangle className="h-5 w-5 text-orange-500" />
                    Confusion Report
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <p className="text-sm text-gray-600 mb-4">
                    Weekly analysis of topics where students struggle most
                  </p>
                  <Button size="sm" variant="outline">
                    View Report
                  </Button>
                </CardContent>
              </Card>

              <Card>
                <CardHeader>
                  <CardTitle className="flex items-center gap-2">
                    <MessageSquare className="h-5 w-5 text-blue-500" />
                    Smart Replies
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <p className="text-sm text-gray-600 mb-4">
                    AI-generated responses to common student questions
                  </p>
                  <Button size="sm" variant="outline">
                    Generate Reply
                  </Button>
                </CardContent>
              </Card>

              <Card>
                <CardHeader>
                  <CardTitle className="flex items-center gap-2">
                    <Zap className="h-5 w-5 text-green-500" />
                    Auto Quiz Generator
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <p className="text-sm text-gray-600 mb-4">
                    Create quizzes automatically from your lesson content
                  </p>
                  <Button size="sm" variant="outline">
                    Create Quiz
                  </Button>
                </CardContent>
              </Card>

              <Card>
                <CardHeader>
                  <CardTitle className="flex items-center gap-2">
                    <BarChart3 className="h-5 w-5 text-purple-500" />
                    Teaching Analytics
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <p className="text-sm text-gray-600 mb-4">
                    Insights on content effectiveness and student engagement
                  </p>
                  <Button size="sm" variant="outline">
                    View Analytics
                  </Button>
                </CardContent>
              </Card>
            </div>
          </TabsContent>

          <TabsContent value="smart-replies">
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <MessageSquare className="h-5 w-5" />
                  Smart Reply Generator
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="space-y-4">
                  <div>
                    <label className="block text-sm font-medium mb-2">Student Question:</label>
                    <Textarea
                      placeholder="Enter the student's question to generate an AI-assisted response..."
                      value={selectedQuestion}
                      onChange={(e) => setSelectedQuestion(e.target.value)}
                      rows={3}
                    />
                  </div>
                  
                  <Button onClick={generateSmartReply} disabled={!selectedQuestion}>
                    <Zap className="mr-2 h-4 w-4" />
                    Generate Smart Reply
                  </Button>
                  
                  {generatedReply && (
                    <div className="border rounded-lg p-4 bg-gray-50">
                      <div className="flex items-center justify-between mb-2">
                        <h4 className="font-medium">AI-Generated Response:</h4>
                        <Button size="sm" variant="outline" onClick={() => navigator.clipboard.writeText(generatedReply)}>
                          <Copy className="h-4 w-4" />
                        </Button>
                      </div>
                      <p className="text-sm">{generatedReply}</p>
                    </div>
                  )}
                </div>
              </CardContent>
            </Card>
          </TabsContent>

          <TabsContent value="quiz-generator">
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <Zap className="h-5 w-5" />
                  Auto-Quiz Generator
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="space-y-4">
                  <div>
                    <label className="block text-sm font-medium mb-2">Topic for Quiz Generation:</label>
                    <Input
                      placeholder="Enter topic (e.g., Quadratic Equations, Fractions, etc.)"
                      value={quizTopic}
                      onChange={(e) => setQuizTopic(e.target.value)}
                    />
                  </div>
                  
                  <div className="flex gap-2">
                    <Button onClick={generateQuiz} disabled={!quizTopic}>
                      <RefreshCw className="mr-2 h-4 w-4" />
                      Generate Quiz
                    </Button>
                    <Button variant="outline">
                      <BookOpen className="mr-2 h-4 w-4" />
                      Analyze Content
                    </Button>
                  </div>
                </div>
              </CardContent>
            </Card>
          </TabsContent>

          <TabsContent value="analytics">
            <div className="grid grid-cols-1 md:grid-cols-4 gap-4 mb-6">
              <Card>
                <CardHeader>
                  <CardTitle className="text-lg flex items-center gap-2">
                    <Users className="h-5 w-5" />
                    Engagement
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="text-2xl font-bold text-blue-600">45min</div>
                  <p className="text-sm text-gray-600">avg session time</p>
                </CardContent>
              </Card>
              
              <Card>
                <CardHeader>
                  <CardTitle className="text-lg flex items-center gap-2">
                    <CheckCircle className="h-5 w-5" />
                    Completion
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="text-2xl font-bold text-green-600">87%</div>
                  <p className="text-sm text-gray-600">completion rate</p>
                </CardContent>
              </Card>
              
              <Card>
                <CardHeader>
                  <CardTitle className="text-lg flex items-center gap-2">
                    <HelpCircle className="h-5 w-5" />
                    Help Requests
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="text-2xl font-bold text-orange-600">23</div>
                  <p className="text-sm text-gray-600">this week</p>
                </CardContent>
              </Card>
              
              <Card>
                <CardHeader>
                  <CardTitle className="text-lg flex items-center gap-2">
                    <MessageSquare className="h-5 w-5" />
                    Forum Activity
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="text-2xl font-bold text-purple-600">156</div>
                  <p className="text-sm text-gray-600">posts this week</p>
                </CardContent>
              </Card>
            </div>

            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <Lightbulb className="h-5 w-5" />
                  AI Recommendations
                </CardTitle>
              </CardHeader>
              <CardContent>
                <ul className="space-y-3">
                  <li className="flex items-start gap-3">
                    <div className="w-6 h-6 rounded-full bg-blue-100 flex items-center justify-center flex-shrink-0 mt-0.5">
                      <span className="text-xs font-bold text-blue-600">1</span>
                    </div>
                    <span className="text-sm">Focus more time on quadratic equations as students show 65% confusion rate</span>
                  </li>
                  <li className="flex items-start gap-3">
                    <div className="w-6 h-6 rounded-full bg-blue-100 flex items-center justify-center flex-shrink-0 mt-0.5">
                      <span className="text-xs font-bold text-blue-600">2</span>
                    </div>
                    <span className="text-sm">Consider adding more visual examples for geometry lessons</span>
                  </li>
                  <li className="flex items-start gap-3">
                    <div className="w-6 h-6 rounded-full bg-blue-100 flex items-center justify-center flex-shrink-0 mt-0.5">
                      <span className="text-xs font-bold text-blue-600">3</span>
                    </div>
                    <span className="text-sm">Your interactive teaching style shows 20% higher engagement than average</span>
                  </li>
                </ul>
              </CardContent>
            </Card>
          </TabsContent>
        </Tabs>
      </div>
    </div>
  );
};

export default AITeachingAssistant;
