import React, { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { Calendar, CheckCircle2, Circle, Clock, Sparkles, AlertTriangle } from 'lucide-react';
import { apiGet, apiPost, API_BASE_URL } from '../lib/apiClient';

interface StudyTask {
  id: number;
  type: 'revision' | 'assignment' | 'practice' | 'video' | 'reading' | 'intervention' | 'live_session' | 'project' | string;
  status: 'pending' | 'in_progress' | 'completed' | 'skipped' | 'rescheduled' | string;
  urgency: 'urgent' | 'normal' | 'optional' | string;
  title: string;
  description?: string;
  estimated_minutes: number;
  subject?: string;
  topic?: string;
}

interface StudyPlan {
  id: number;
  week_start: string;
  week_end: string;
  total_estimated_minutes: number;
  completed_minutes: number;
}

const URGENCY_BADGE: Record<string, string> = {
  urgent:   'bg-rose-50 text-rose-700 border-rose-200',
  normal:   'bg-indigo-50 text-indigo-700 border-indigo-200',
  optional: 'bg-slate-100 text-slate-700 border-slate-200',
};

/**
 * Personalised learning path — bound to the intelligence app's study
 * planner. Renders today's tasks first, with a "Generate this week"
 * fallback when no plan exists yet.
 */
const LearningPathPage: React.FC = () => {
  const [tasks, setTasks] = useState<StudyTask[]>([]);
  const [plans, setPlans] = useState<StudyPlan[]>([]);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const refresh = async () => {
    setLoading(true);
    setError(null);
    const [todayResp, plansResp] = await Promise.all([
      apiGet<any>(`${API_BASE_URL}/api/v1/intelligence/study-plans/today/`),
      apiGet<any>(`${API_BASE_URL}/api/v1/intelligence/study-plans/`),
    ]);
    if (todayResp.error) {
      setError(todayResp.error.message);
    } else {
      const arr = Array.isArray(todayResp.data) ? todayResp.data : ((todayResp.data as any)?.results || []);
      setTasks(arr as StudyTask[]);
    }
    if (!plansResp.error) {
      const arr = Array.isArray(plansResp.data) ? plansResp.data : ((plansResp.data as any)?.results || []);
      setPlans(arr as StudyPlan[]);
    }
    setLoading(false);
  };

  useEffect(() => { void refresh(); }, []);

  const onGenerate = async () => {
    setGenerating(true);
    await apiPost<StudyPlan>(`${API_BASE_URL}/api/v1/intelligence/study-plans/generate/`, {});
    setGenerating(false);
    await refresh();
  };

  const onComplete = async (taskId: number) => {
    await apiPost<StudyTask>(
      `${API_BASE_URL}/api/v1/intelligence/study-tasks/${taskId}/complete/`,
      {},
    );
    await refresh();
  };

  const totals = useMemo(() => {
    const minutes = tasks.reduce((s, t) => s + (t.estimated_minutes || 0), 0);
    const done = tasks.filter((t) => t.status === 'completed').length;
    return { minutes, done, total: tasks.length };
  }, [tasks]);

  const currentPlan = plans[0];

  return (
    <div className="container mx-auto px-4 py-8 max-w-4xl">
      <header className="mb-6">
        <p className="text-xs font-bold uppercase tracking-wider text-slate-500">Learning path</p>
        <h1 className="mt-1 text-3xl font-extrabold text-slate-900">Today's plan</h1>
        <p className="mt-2 text-slate-600">
          A short stack of tasks generated by Maple Intelligence — based on your weakest topics, attendance, and assessment trend.
        </p>
      </header>

      {error && (
        <div className="mb-4 flex items-start gap-2 rounded-lg border border-rose-200 bg-rose-50 p-4">
          <AlertTriangle className="w-5 h-5 text-rose-600 flex-shrink-0 mt-0.5" />
          <div>
            <p className="font-medium text-rose-800">Could not load your plan.</p>
            <p className="text-sm text-rose-700 mt-1">{error}</p>
          </div>
        </div>
      )}

      {loading ? (
        <div className="space-y-3">
          {[0, 1, 2].map((i) => (
            <div key={i} className="h-20 rounded-xl bg-slate-100 animate-pulse" />
          ))}
        </div>
      ) : tasks.length === 0 ? (
        <div className="rounded-2xl border border-slate-200 bg-white p-8 text-center">
          <Sparkles className="w-8 h-8 text-amber-500 mx-auto" />
          <h2 className="mt-3 text-lg font-bold text-slate-900">No plan for today yet</h2>
          <p className="mt-1 text-sm text-slate-600 max-w-sm mx-auto">
            Generate a fresh weekly plan based on your strongest and weakest subjects.
          </p>
          <button
            type="button"
            onClick={onGenerate}
            disabled={generating}
            className="mt-4 inline-flex items-center gap-2 rounded-full bg-slate-900 px-5 py-2.5 text-sm font-semibold text-white disabled:opacity-60"
          >
            <Sparkles className="w-4 h-4" />
            {generating ? 'Generating…' : "Generate this week's plan"}
          </button>
        </div>
      ) : (
        <>
          {currentPlan && (
            <div className="mb-4 rounded-2xl border border-slate-200 bg-white p-4 flex items-center gap-4">
              <Calendar className="w-5 h-5 text-slate-500" />
              <div className="flex-1">
                <p className="text-sm font-semibold text-slate-900">
                  Week of {new Date(currentPlan.week_start).toLocaleDateString()}
                </p>
                <p className="text-xs text-slate-500">
                  {totals.done} / {totals.total} done · {totals.minutes} minutes planned today
                </p>
              </div>
              <button
                type="button"
                onClick={onGenerate}
                disabled={generating}
                className="text-xs font-bold uppercase tracking-wider text-slate-700 hover:text-slate-900 disabled:opacity-60"
              >
                Re-plan
              </button>
            </div>
          )}

          <div className="space-y-2">
            {tasks.map((t) => <TaskRow key={t.id} task={t} onComplete={() => onComplete(t.id)} />)}
          </div>

          <p className="mt-6 text-center">
            <Link to="/dashboard/student" className="text-sm font-medium text-slate-600 hover:text-slate-900">
              ← Back to dashboard
            </Link>
          </p>
        </>
      )}
    </div>
  );
};

const TaskRow: React.FC<{ task: StudyTask; onComplete: () => void }> = ({ task, onComplete }) => {
  const completed = task.status === 'completed';
  const badgeClass = URGENCY_BADGE[task.urgency] || URGENCY_BADGE.normal;
  return (
    <div className={`rounded-xl border bg-white p-4 ${completed ? 'opacity-60' : 'border-slate-200'}`}>
      <div className="flex items-start gap-3">
        <button
          type="button"
          onClick={completed ? undefined : onComplete}
          disabled={completed}
          aria-label={`Mark ${task.title} complete`}
          className="mt-0.5"
        >
          {completed ? (
            <CheckCircle2 className="w-5 h-5 text-emerald-600" />
          ) : (
            <Circle className="w-5 h-5 text-slate-400 hover:text-slate-600 transition-colors" />
          )}
        </button>
        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-2 mb-1">
            <span className={`text-[10px] font-bold uppercase tracking-wider px-2 py-0.5 rounded border ${badgeClass}`}>
              {task.urgency}
            </span>
            {task.subject && (
              <span className="text-xs text-slate-500">{task.subject}</span>
            )}
          </div>
          <p className={`text-sm font-semibold text-slate-900 ${completed ? 'line-through' : ''}`}>
            {task.title}
          </p>
          {task.description && (
            <p className="mt-1 text-xs text-slate-600 line-clamp-2">{task.description}</p>
          )}
          <div className="mt-2 flex items-center gap-3 text-xs text-slate-500">
            <span className="inline-flex items-center gap-1">
              <Clock className="w-3 h-3" />
              {task.estimated_minutes} min
            </span>
            <span>{task.type.replace('_', ' ')}</span>
          </div>
        </div>
      </div>
    </div>
  );
};

export default LearningPathPage;
