# Generated by Django 6.0.4 on 2026-04-24 03:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0003_add_title_instructions_created_by_is_published'),
        ('curriculum', '0004_classlevel_internal_canonical_grade_and_more'),
        ('live_sessions', '0002_missedsessionrecovery_recoveryassignment'),
        ('resources', '0004_content_assignment_engagement_system'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MasteryTrack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=280, unique=True)),
                ('description', models.TextField(blank=True)),
                ('tagline', models.CharField(blank=True, help_text='One-line benefit statement shown on cards.', max_length=255)),
                ('target_role', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('parent', 'Parent')], default='student', max_length=20)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('exam_track', models.CharField(blank=True, choices=[('', 'None'), ('PLE', 'PLE'), ('UCE', 'UCE'), ('UACE', 'UACE'), ('KCSE', 'KCSE'), ('general', 'General')], default='', max_length=20)),
                ('estimated_duration_weeks', models.PositiveIntegerField(default=4)),
                ('estimated_hours_per_week', models.PositiveIntegerField(default=3)),
                ('is_published', models.BooleanField(default=False)),
                ('is_premium', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('cover_image', models.URLField(blank=True, help_text='Optional cover image URL.')),
                ('outcome_statement', models.TextField(blank=True, help_text='What the learner will be able to do after finishing.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='curriculum.classlevel')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='curriculum.country')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_mastery_tracks', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='curriculum.subject')),
            ],
            options={
                'ordering': ['-is_featured', 'title'],
            },
        ),
        migrations.CreateModel(
            name='MasteryEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('active', 'Active'), ('completed', 'Completed'), ('paused', 'Paused')], default='active', max_length=20)),
                ('completed_item_ids', models.JSONField(blank=True, default=list)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mastery_enrollments', to=settings.AUTH_USER_MODEL)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='mastery.masterytrack')),
            ],
            options={
                'ordering': ['-last_activity_at'],
            },
        ),
        migrations.CreateModel(
            name='MasteryTrackModule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='mastery.masterytrack')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MasteryTrackItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('content', 'Content / Lesson'), ('assessment', 'Assessment / Quiz'), ('practice_lab', 'Guided Practice Lab'), ('project', 'Mastery Project'), ('live_session', 'Live Session')], max_length=20)),
                ('placeholder_title', models.CharField(blank=True, help_text='Used for practice_lab/project items until their models land.', max_length=255)),
                ('placeholder_description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('required_for_completion', models.BooleanField(default=True)),
                ('assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mastery_track_items', to='assessments.assessment')),
                ('content_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mastery_track_items', to='resources.contentitem')),
                ('live_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mastery_track_items', to='live_sessions.livesession')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='mastery.masterytrackmodule')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='masterytrack',
            index=models.Index(fields=['is_published', 'target_role'], name='mastery_mas_is_publ_d949c8_idx'),
        ),
        migrations.AddIndex(
            model_name='masterytrack',
            index=models.Index(fields=['subject', 'class_level'], name='mastery_mas_subject_72fb3c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='masteryenrollment',
            unique_together={('learner', 'track')},
        ),
        migrations.AlterUniqueTogether(
            name='masterytrackmodule',
            unique_together={('track', 'order')},
        ),
    ]
