# Generated by Django 6.0.4 on 2026-04-24 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mastery', '0001_initial'),
        ('practice_labs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterytrackitem',
            name='practice_lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mastery_track_items', to='practice_labs.practicelab'),
        ),
    ]
