# Generated by Django 6.0.4 on 2026-04-24 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mastery', '0002_masterytrackitem_practice_lab'),
        ('mastery_projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterytrackitem',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mastery_track_items', to='mastery_projects.masteryproject'),
        ),
    ]
