# Generated by Django 4.2.29 on 2026-04-05 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplace', '0001_initial'),
        ('institutions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionBillingPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('termly', 'Termly'), ('yearly', 'Yearly')], max_length=20)),
                ('price_per_student', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='UGX', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='UGX', max_length=10)),
                ('description', models.CharField(max_length=255)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('institution', models.ForeignKey(blank=True, help_text='The paying entity (Institution Mode)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='institutions.institution')),
                ('user', models.ForeignKey(blank=True, help_text='The individual payer (Platform Fee, Subject Subscription)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherAccessFeeAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_obligation', models.DecimalField(decimal_places=2, default=300000.0, max_digits=12)),
                ('recovered_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('is_recovered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access_fee_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pesapal_tracking_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('pesapal_merchant_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='UGX', max_length=10)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('completed', 'Completed/Verified'), ('failed', 'Failed'), ('reversed', 'Reversed')], default='initiated', max_length=20)),
                ('payment_method', models.CharField(blank=True, help_text='MTN Mobile Money, Airtel Money, Visa', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='billing.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherFeeInstallment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_deducted', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='billing.teacheraccessfeeaccount')),
                ('payout_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_installments', to='marketplace.teacherpayoutbatch')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectClassProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('monthly_price', models.DecimalField(decimal_places=2, default=50000.0, max_digits=12)),
                ('currency', models.CharField(default='UGX', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_purchasable', models.BooleanField(default=True)),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_products', to='curriculum.classlevel')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_products', to='curriculum.subject')),
            ],
            options={
                'unique_together': {('subject', 'class_level')},
            },
        ),
        migrations.CreateModel(
            name='StudentSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending_payment', 'Pending Payment'), ('active', 'Active'), ('grace_period', 'Grace Period'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending_payment', max_length=20)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribed_students', to='billing.subjectclassproduct')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionBillingProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activation_status', models.CharField(choices=[('setup', 'Free Setup Mode'), ('active', 'Fully Activated'), ('grace_period', 'Grace Period (Overage)'), ('suspended', 'Suspended')], default='setup', max_length=20)),
                ('paid_seat_count', models.IntegerField(default=0, help_text='How many active student seats this institution has currently paid for')),
                ('currency', models.CharField(default='UGX', max_length=10)),
                ('next_billing_date', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.institutionbillingplan')),
                ('institution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_profile', to='institutions.institution')),
            ],
        ),
    ]
