# Generated by Django 4.2.29 on 2026-04-08 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scheduling', '0002_timetableslot_is_draft_timetableslot_subject_and_more'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherLessonNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatched_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_notifications', to=settings.AUTH_USER_MODEL)),
                ('timetable_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.timetableslot')),
            ],
        ),
    ]
