# Generated by Django 6.0.4 on 2026-04-24 02:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0004_classlevel_internal_canonical_grade_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('started', 'Started'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('abandoned', 'Abandoned')], default='started', max_length=20)),
                ('sampled_question_ids', models.JSONField(blank=True, default=list)),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('grades', models.JSONField(blank=True, default=dict)),
                ('total_questions', models.IntegerField(default=0)),
                ('correct_count', models.IntegerField(default=0)),
                ('score_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('per_subject_scores', models.JSONField(blank=True, default=list)),
                ('per_topic_scores', models.JSONField(blank=True, default=list)),
                ('report_data', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('class_level', models.ForeignKey(blank=True, help_text='The class-level the student says they are joining from. Drives question sampling.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnostic_sessions', to='curriculum.classlevel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['student', 'state'], name='diagnostics_student_adccf5_idx')],
            },
        ),
    ]
