# Generated by Django 6.0.4 on 2026-04-24 03:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0004_classlevel_internal_canonical_grade_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeLab',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=280, unique=True)),
                ('description', models.TextField(blank=True)),
                ('instructions', models.TextField(blank=True, help_text='Shown at the start of the lab.')),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('estimated_minutes', models.PositiveIntegerField(default=15)),
                ('pass_threshold_pct', models.PositiveIntegerField(default=70, help_text='Min % to pass and earn the badge.')),
                ('badge_label', models.CharField(blank=True, help_text='e.g. "Fluency Starter"', max_length=120)),
                ('is_published', models.BooleanField(default=False)),
                ('is_premium', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='curriculum.classlevel')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_practice_labs', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='curriculum.subject')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='curriculum.topic')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PracticeLabAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('started', 'Started'), ('submitted', 'Submitted'), ('completed', 'Completed'), ('needs_retry', 'Needs Retry')], default='started', max_length=20)),
                ('score_points', models.PositiveIntegerField(default=0)),
                ('max_points', models.PositiveIntegerField(default=0)),
                ('score_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('feedback', models.TextField(blank=True)),
                ('badge_earned', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='practice_labs.practicelab')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_lab_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PracticeLabStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(default=1)),
                ('step_type', models.CharField(choices=[('instruction', 'Instruction'), ('question', 'Open Question'), ('reflection', 'Reflection'), ('upload', 'File Upload'), ('short_answer', 'Short Answer'), ('mcq', 'Multiple Choice')], max_length=20)),
                ('prompt', models.TextField()),
                ('hint', models.TextField(blank=True)),
                ('options', models.JSONField(blank=True, default=list, help_text='MCQ options.')),
                ('expected_answer', models.CharField(blank=True, help_text='For mcq + short_answer auto-grading.', max_length=500)),
                ('points', models.PositiveIntegerField(default=1)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='practice_labs.practicelab')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PracticeLabStepResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('response_text', models.TextField(blank=True)),
                ('selected_option', models.CharField(blank=True, max_length=500)),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='practice_labs/uploads/')),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='practice_labs.practicelabattempt')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='practice_labs.practicelabstep')),
            ],
        ),
        migrations.AddIndex(
            model_name='practicelabattempt',
            index=models.Index(fields=['student', 'lab'], name='practice_la_student_6d2fd9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='practicelabstep',
            unique_together={('lab', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='practicelabstepresponse',
            unique_together={('attempt', 'step')},
        ),
    ]
