# Generated by Django 6.0.4 on 2026-04-24 03:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0004_classlevel_internal_canonical_grade_and_more'),
        ('institutions', '0007_subscriptionplan_learnerregistration_completed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_term', models.CharField(blank=True, help_text='e.g. "Term 1 2026"', max_length=60)),
                ('study_mode', models.CharField(blank=True, choices=[('day', 'Day'), ('boarding', 'Boarding'), ('hybrid', 'Hybrid')], max_length=20)),
                ('current_school', models.CharField(blank=True, max_length=255)),
                ('academic_summary', models.TextField(blank=True)),
                ('share_passport', models.BooleanField(default=True)),
                ('shared_passport_token', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('more_info_requested', 'More Info Requested'), ('interview_invited', 'Interview Invited'), ('accepted', 'Accepted'), ('waitlisted', 'Waitlisted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='draft', max_length=30)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='curriculum.classlevel')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_applications', to='institutions.institution')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_admission_applications', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionStatusEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, max_length=30)),
                ('to_status', models.CharField(max_length=30)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='admission_passport.admissionapplication')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='admissionapplication',
            index=models.Index(fields=['student', 'status'], name='admission_p_student_7ef479_idx'),
        ),
        migrations.AddIndex(
            model_name='admissionapplication',
            index=models.Index(fields=['institution', 'status'], name='admission_p_institu_2f630e_idx'),
        ),
    ]
