# Generated by Django 6.0.4 on 2026-04-24 07:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UpgradeRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan', models.CharField(choices=[('learner_plus', 'Learner Plus'), ('parent_premium', 'Parent Premium'), ('teacher_pro', 'Teacher Pro'), ('school_os', 'School OS'), ('school_os_plus', 'School OS Plus')], max_length=30)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('preferred_method', models.CharField(blank=True, choices=[('mtn_momo', 'MTN Mobile Money'), ('airtel_money', 'Airtel Money'), ('cash', 'Cash / Bank Transfer'), ('other', 'Other')], max_length=20)),
                ('note', models.TextField(blank=True, help_text='Anything the admin should know.')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upgrade_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_upgrade_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PremiumAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan', models.CharField(choices=[('learner_plus', 'Learner Plus'), ('parent_premium', 'Parent Premium'), ('teacher_pro', 'Teacher Pro'), ('school_os', 'School OS'), ('school_os_plus', 'School OS Plus')], max_length=30)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Leave blank for open-ended.', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premium_accesses', to=settings.AUTH_USER_MODEL)),
                ('source_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grants', to='pilot_payments.upgraderequest')),
            ],
            options={
                'ordering': ['-granted_at'],
            },
        ),
        migrations.AddIndex(
            model_name='upgraderequest',
            index=models.Index(fields=['status', 'plan'], name='pilot_payme_status_97c582_idx'),
        ),
        migrations.AddIndex(
            model_name='upgraderequest',
            index=models.Index(fields=['requester', 'status'], name='pilot_payme_request_7e2bb1_idx'),
        ),
        migrations.AddIndex(
            model_name='premiumaccess',
            index=models.Index(fields=['user', 'plan'], name='pilot_payme_user_id_98b011_idx'),
        ),
    ]
