# Generated by Django 4.2.29 on 2026-04-27 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot_payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upgraderequest',
            name='preferred_method',
            field=models.CharField(blank=True, choices=[('mtn_momo', 'MTN Mobile Money'), ('airtel_money', 'Airtel Money'), ('mpesa', 'M-Pesa'), ('cash', 'Cash / Bank Transfer'), ('other', 'Other')], max_length=20),
        ),
    ]
