# Generated by Django 4.2.29 on 2026-04-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.TextField(blank=True, help_text='Correct answer string or index for auto-grading'),
        ),
        migrations.AddField(
            model_name='question',
            name='options',
            field=models.JSONField(blank=True, default=list, help_text='List of choices for MCQ'),
        ),
        migrations.AddField(
            model_name='submission',
            name='answers_data',
            field=models.JSONField(blank=True, default=dict, help_text='Store student submitted answers keyed by question ID'),
        ),
        migrations.AddField(
            model_name='submission',
            name='total_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
