# Generated by Django 4.2.29 on 2026-04-08 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_academicyear'),
        ('institutions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scheduling', '0001_initial'),
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfflineAcademicResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=255)),
                ('score_pct', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('online_mastery_at_time', models.DecimalField(decimal_places=2, default=0.0, help_text='Snapshot of online performance when this was recorded', max_digits=5)),
                ('date_recorded', models.DateField(db_index=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.institution')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offline_results', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.subject')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduling.academicterm')),
            ],
        ),
        migrations.CreateModel(
            name='NationalExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cohort_year', models.IntegerField(help_text='e.g. 2024')),
                ('exam_type', models.CharField(choices=[('UCE', 'UCE'), ('UACE', 'UACE'), ('PLE', 'PLE')], max_length=50)),
                ('total_candidates', models.IntegerField(default=0)),
                ('division_1_count', models.IntegerField(default=0)),
                ('division_2_count', models.IntegerField(default=0)),
                ('division_3_count', models.IntegerField(default=0)),
                ('division_4_count', models.IntegerField(default=0)),
                ('failures_count', models.IntegerField(default=0)),
                ('year_over_year_improvement_pct', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='national_exam_results', to='institutions.institution')),
            ],
        ),
    ]
