# Generated by Django 4.2.29 on 2026-04-02 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
        ('assessments', '0002_question_correct_answer_question_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='max_score',
            field=models.DecimalField(decimal_places=2, default=100.0, help_text='Used for weighting external exams', max_digits=5),
        ),
        migrations.AddField(
            model_name='assessment',
            name='source',
            field=models.CharField(choices=[('platform_quiz', 'Platform Quiz'), ('manual_school_test', 'Manual School Test'), ('manual_exam', 'Manual Exam'), ('practical', 'Practical'), ('project', 'Project'), ('oral', 'Oral'), ('imported_csv', 'Imported CSV')], default='platform_quiz', max_length=50),
        ),
        migrations.AddField(
            model_name='assessment',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='scheduling.academicterm'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='window',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='assessments.assessmentwindow'),
        ),
    ]
