# Generated by Django 4.2.29 on 2026-04-23 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assessments', '0002_offlineacademicresult_nationalexamresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_assessments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessment',
            name='instructions',
            field=models.TextField(blank=True, default='', help_text='Prompt / question body the student reads'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Students only see published assessments'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='title',
            field=models.CharField(default='Untitled assignment', max_length=255),
        ),
    ]
