# Generated by Django 4.2.29 on 2026-04-02 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('institutions', '0004_teacherqualityscore_subscriptionledger_and_more'),
        ('curriculum', '0002_curriculumversion_resourcequalityreview_and_more'),
        ('assessments', '0003_assessment_max_score_assessment_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentTargetGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="e.g. 'Remedial Biology Group A'", max_length=255)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_target_groups', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.institution')),
                ('students', models.ManyToManyField(related_name='targeted_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reasoning', models.TextField(help_text="e.g. '12 students failed the previous assessment on this topic.'")),
                ('is_accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recommended_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.topic')),
                ('suggested_target_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assessments.assignmenttargetgroup')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='assessment',
            name='target_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_assessments', to='assessments.assignmenttargetgroup'),
        ),
    ]
