# Generated by Django 4.2.29 on 2026-04-05 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_year', models.CharField(max_length=10)),
                ('exam_type', models.CharField(choices=[('UCE', 'UCE'), ('UACE', 'UACE')], default='UCE', max_length=10)),
                ('documents', models.JSONField(default=dict, help_text='Mock payload holding file meta')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='exams.candidateregistration')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.subject')),
            ],
        ),
        migrations.CreateModel(
            name='ExamCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_name', models.CharField(max_length=50)),
                ('center_number', models.CharField(max_length=50)),
                ('name', models.CharField(default='Unnamed Center', max_length=255)),
                ('location', models.JSONField(default=dict)),
                ('capacity', models.JSONField(default=dict)),
                ('fees', models.JSONField(default=dict)),
                ('facilities', models.JSONField(default=list)),
                ('performance_history', models.JSONField(default=list)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_centers', to='institutions.institution')),
            ],
        ),
        migrations.AddField(
            model_name='candidateregistration',
            name='exam_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='exams.examcenter'),
        ),
        migrations.AddField(
            model_name='candidateregistration',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_registrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BoardSubmissionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_payload', models.JSONField(help_text='Finalized JSON dump of all candidates matching board spec')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('exam_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_batches', to='exams.examcenter')),
            ],
        ),
    ]
