# Generated by Django 4.2.29 on 2026-04-02 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateregistration',
            name='documents',
            field=models.JSONField(default=dict, help_text='Mock payload holding file meta'),
        ),
        migrations.AddField(
            model_name='candidateregistration',
            name='exam_type',
            field=models.CharField(choices=[('UCE', 'UCE'), ('UACE', 'UACE')], default='UCE', max_length=10),
        ),
        migrations.AddField(
            model_name='examcenter',
            name='capacity',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='examcenter',
            name='facilities',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='examcenter',
            name='fees',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='examcenter',
            name='location',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='examcenter',
            name='name',
            field=models.CharField(default='Unnamed Center', max_length=255),
        ),
        migrations.AddField(
            model_name='examcenter',
            name='performance_history',
            field=models.JSONField(default=list),
        ),
    ]
