# Generated by Django 4.2.29 on 2026-04-02 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='subject',
        ),
    ]
