# Generated by Django 4.2.29 on 2026-04-02 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0003_institutionsubject'),
        ('classes', '0002_remove_class_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='institution_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='institutions.institutionsubject'),
        ),
    ]
