# Generated by Django 4.2.29 on 2026-04-05 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons', '0001_initial'),
        ('institutions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('curriculum', '0001_initial'),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_type', models.CharField(choices=[('platform', 'Platform Global'), ('institution', 'Institution Scope'), ('teacher', 'Teacher Personal')], default='teacher', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('file_path', models.FileField(blank=True, null=True, upload_to='resources/')),
                ('external_url', models.URLField(blank=True, max_length=500, null=True)),
                ('vimeo_upload_status', models.CharField(choices=[('none', 'Not Applicable'), ('pending', 'Pending Upload'), ('processing', 'Processing on Vimeo'), ('completed', 'Completed'), ('failed', 'Upload Failed')], default='none', max_length=20)),
                ('vimeo_video_id', models.CharField(blank=True, max_length=50, null=True)),
                ('visibility', models.CharField(choices=[('private', 'Private Internal'), ('institution_only', 'Institution Only'), ('platform_shared', 'Platform Shared (OER)'), ('marketplace_public', 'Marketplace Public')], default='private', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='curriculum.classlevel')),
                ('owner_institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_resources', to='institutions.institution')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='curriculum.subject')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='curriculum.topic')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_resources', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SharedResourceLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_resource_links', to=settings.AUTH_USER_MODEL)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_links', to='resources.resource')),
                ('target_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_links', to='classes.class')),
            ],
            options={
                'unique_together': {('resource', 'target_class')},
            },
        ),
        migrations.CreateModel(
            name='ResourceLessonLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('core_note', 'Core Teaching Note'), ('presentation', 'Presentation/Slides'), ('reading', 'Recommended Reading'), ('worksheet', 'Worksheet'), ('assignment', 'Assignment'), ('other', 'Other material')], default='other', max_length=50)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_links', to='lessons.lesson')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_links', to='resources.resource')),
            ],
            options={
                'unique_together': {('resource', 'lesson')},
            },
        ),
        migrations.CreateModel(
            name='ResourceEngagementRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_by', models.CharField(choices=[('teacher', 'Teacher Assigned'), ('intervention', 'Intervention System'), ('self', 'Self-Selected'), ('system', 'System Recommended')], default='self', max_length=20)),
                ('total_active_time_mins', models.IntegerField(default=0, help_text='Cumulative active minutes tracked by frontend hook')),
                ('completion_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('last_position', models.IntegerField(default=0, help_text='Scroll position or video timestamp in seconds')),
                ('is_completed', models.BooleanField(default=False)),
                ('first_opened', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_records', to='resources.resource')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_engagements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'resource')},
            },
        ),
    ]
