# Generated by Django 4.2.29 on 2026-04-10 13:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import resources.content_models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interventions', '0002_interventioneffectivenesstracker'),
        ('assessments', '0002_offlineacademicresult_nationalexamresult'),
        ('curriculum', '0004_classlevel_internal_canonical_grade_and_more'),
        ('lessons', '0002_lessoninstance_lessonverificationrecord'),
        ('classes', '0001_initial'),
        ('institutions', '0005_alter_institution_school_level'),
        ('resources', '0002_add_frontend_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('content_type', models.CharField(choices=[('notes', 'Notes'), ('textbook', 'Textbook'), ('pdf', 'PDF Document'), ('document', 'Word/Document'), ('video', 'Video'), ('slides', 'Slide Deck / Presentation'), ('worksheet', 'Worksheet'), ('assignment', 'Assignment'), ('project', 'Project'), ('activity', 'Activity'), ('revision', 'Revision Resource'), ('teacher_guide', 'Teacher Guide'), ('lesson_attachment', 'Lesson Attachment'), ('topic_resource', 'Topic Resource'), ('class_resource', 'Class Resource'), ('library_resource', 'Library Resource'), ('mock_exam', 'Mock Exam Resource'), ('intervention', 'Intervention Resource'), ('other', 'Other')], max_length=30)),
                ('owner_type', models.CharField(choices=[('teacher', 'Teacher'), ('institution', 'Institution Admin'), ('platform_admin', 'Platform Admin')], default='teacher', max_length=20)),
                ('school_level', models.CharField(blank=True, default='', help_text='primary or secondary', max_length=20)),
                ('visibility_scope', models.CharField(choices=[('global', 'Global / Platform-wide'), ('country', 'Country-wide'), ('institution', 'Institution-wide'), ('class', 'Class-specific'), ('assigned_students', 'Assigned Students Only'), ('private', 'Private / Draft')], default='private', max_length=30)),
                ('publication_status', models.CharField(choices=[('draft', 'Draft'), ('uploaded', 'Uploaded'), ('processing', 'Processing'), ('under_review', 'Under Review'), ('published', 'Published'), ('archived', 'Archived'), ('rejected', 'Rejected'), ('hidden', 'Hidden')], default='draft', max_length=20)),
                ('moderation_status', models.CharField(blank=True, default='', help_text='approved, rejected, pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('file', models.FileField(blank=True, null=True, upload_to=resources.content_models.content_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'doc', 'pptx', 'ppt', 'xlsx', 'xls', 'mp4', 'mov', 'avi', 'mkv', 'webm', 'm4v', 'jpg', 'jpeg', 'png', 'gif', 'webp', 'svg', 'zip', 'txt', 'csv'])])),
                ('external_url', models.URLField(blank=True, default='', max_length=1000)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=resources.content_models.content_thumbnail_path)),
                ('mime_type', models.CharField(blank=True, default='', max_length=100)),
                ('file_size', models.BigIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('duration_seconds', models.IntegerField(blank=True, help_text='Duration for video/audio content in seconds', null=True)),
                ('vimeo_video_id', models.CharField(blank=True, default='', max_length=50)),
                ('vimeo_upload_status', models.CharField(blank=True, default='none', max_length=20)),
                ('language', models.CharField(blank=True, default='en', max_length=10)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_attachments', to='assessments.assessment')),
                ('class_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_items', to='curriculum.classlevel')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_items', to='curriculum.country')),
                ('curriculum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_items', to='curriculum.curriculumtrack')),
                ('education_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_items', to='curriculum.educationlevel')),
                ('intervention', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_attachments', to='interventions.interventionplan')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_items', to='lessons.lesson')),
                ('owner_institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_items', to='institutions.institution')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_items', to='curriculum.subject')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_items', to='curriculum.topic')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_items_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContentVisibilityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visibility_rules', to='resources.contentitem')),
                ('target_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visible_content_rules', to='classes.class')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_content_rules', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContentEngagement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('active_time_seconds', models.PositiveIntegerField(default=0)),
                ('completion_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('last_position', models.IntegerField(default=0, help_text='Scroll pos or video timestamp (seconds)')),
                ('is_completed', models.BooleanField(default=False)),
                ('first_accessed', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('content_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagements', to='resources.contentitem')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institutions.institution')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_engagements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_accessed'],
            },
        ),
        migrations.CreateModel(
            name='ContentAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Metadata Updated'), ('file_replaced', 'File Replaced'), ('published', 'Published'), ('archived', 'Archived'), ('rejected', 'Rejected'), ('deleted', 'Deleted'), ('moderated', 'Moderated'), ('visibility_changed', 'Visibility Changed'), ('restored', 'Restored')], max_length=30)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='resources.contentitem')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_audit_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ContentVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('file', models.FileField(blank=True, null=True, upload_to='content/versions/')),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, default='', max_length=100)),
                ('change_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='resources.contentitem')),
                ('replaced_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_version_replacements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version_number'],
                'unique_together': {('content_item', 'version_number')},
            },
        ),
        migrations.CreateModel(
            name='ContentItemTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_tags', to='resources.contentitem')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='resources.contenttag')),
            ],
            options={
                'unique_together': {('content_item', 'tag')},
            },
        ),
        migrations.AddIndex(
            model_name='contentitem',
            index=models.Index(fields=['publication_status', 'visibility_scope'], name='resources_c_publica_a90df9_idx'),
        ),
        migrations.AddIndex(
            model_name='contentitem',
            index=models.Index(fields=['owner_institution', 'school_level'], name='resources_c_owner_i_b5e324_idx'),
        ),
        migrations.AddIndex(
            model_name='contentitem',
            index=models.Index(fields=['content_type'], name='resources_c_content_ff8950_idx'),
        ),
        migrations.AddIndex(
            model_name='contentitem',
            index=models.Index(fields=['subject', 'class_level'], name='resources_c_subject_b62154_idx'),
        ),
        migrations.AddIndex(
            model_name='contentitem',
            index=models.Index(fields=['uploaded_by'], name='resources_c_uploade_e2e0d1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contentengagement',
            unique_together={('student', 'content_item')},
        ),
    ]
