# Generated by Django 4.2.29 on 2026-04-11 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_lessoninstance_lessonverificationrecord'),
        ('curriculum', '0004_classlevel_internal_canonical_grade_and_more'),
        ('classes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resources', '0003_contentitem_contenttag_contentvisibilityrule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentAccessSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_started_at', models.DateTimeField(auto_now_add=True)),
                ('session_ended_at', models.DateTimeField(blank=True, null=True)),
                ('active_seconds', models.PositiveIntegerField(default=0)),
                ('interaction_type', models.CharField(choices=[('document', 'Document / Notes / PDF'), ('video', 'Video'), ('interactive', 'Interactive / Exercise'), ('slides', 'Slides / Presentation'), ('other', 'Other')], default='document', max_length=20)),
                ('client_type', models.CharField(default='web', help_text='web or app', max_length=10)),
                ('progress_at_start', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('progress_at_end', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('position_at_end', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-session_started_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_by_type', models.CharField(choices=[('teacher', 'Teacher'), ('ai', 'AI Engine'), ('institution', 'Institution'), ('platform', 'Platform')], default='teacher', max_length=20)),
                ('assignment_type', models.CharField(choices=[('required', 'Required'), ('recommended', 'Recommended')], default='required', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('note', models.TextField(blank=True, default='', help_text='Reason or instruction for the student')),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('ai_weak_topic', 'AI - Weak Topic'), ('ai_exam_readiness', 'AI - Exam Readiness'), ('ai_missed_lesson', 'AI - Missed Lesson'), ('ai_low_engagement', 'AI - Low Engagement'), ('ai_practice_gap', 'AI - Practice Gap'), ('teacher', 'Teacher Recommendation'), ('institution', 'Institution Recommendation'), ('platform', 'Platform Curated')], max_length=30)),
                ('reason', models.TextField(blank=True, default='', help_text='Human-readable explanation')),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0.8, help_text='AI confidence 0-1', max_digits=4)),
                ('status', models.CharField(choices=[('active', 'Active'), ('dismissed', 'Dismissed'), ('accepted', 'Accepted'), ('expired', 'Expired')], default='active', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='contentengagement',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentengagement',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('started', 'Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20),
        ),
        migrations.AlterField(
            model_name='contentengagement',
            name='first_accessed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contentengagement',
            name='last_accessed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='contentengagement',
            index=models.Index(fields=['student', 'status'], name='resources_c_student_74c966_idx'),
        ),
        migrations.AddIndex(
            model_name='contentengagement',
            index=models.Index(fields=['content_item', 'status'], name='resources_c_content_e1f38c_idx'),
        ),
        migrations.AddField(
            model_name='contentrecommendation',
            name='content_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='resources.contentitem'),
        ),
        migrations.AddField(
            model_name='contentrecommendation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_recommendations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contentrecommendation',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_recommendations', to='curriculum.subject'),
        ),
        migrations.AddField(
            model_name='contentrecommendation',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_recommendations', to='curriculum.topic'),
        ),
        migrations.AddField(
            model_name='contentassignment',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_assignments_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contentassignment',
            name='content_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='resources.contentitem'),
        ),
        migrations.AddField(
            model_name='contentassignment',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_assignments', to='lessons.lesson'),
        ),
        migrations.AddField(
            model_name='contentassignment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contentassignment',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_assignments', to='curriculum.subject'),
        ),
        migrations.AddField(
            model_name='contentassignment',
            name='target_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_assignments', to='classes.class'),
        ),
        migrations.AddField(
            model_name='contentassignment',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_assignments', to='curriculum.topic'),
        ),
        migrations.AddField(
            model_name='contentaccesssession',
            name='content_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_sessions', to='resources.contentitem'),
        ),
        migrations.AddField(
            model_name='contentaccesssession',
            name='engagement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='resources.contentengagement'),
        ),
        migrations.AddField(
            model_name='contentaccesssession',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_access_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='contentrecommendation',
            index=models.Index(fields=['student', 'status'], name='resources_c_student_a9b5e4_idx'),
        ),
        migrations.AddIndex(
            model_name='contentrecommendation',
            index=models.Index(fields=['source'], name='resources_c_source_20ef56_idx'),
        ),
        migrations.AddIndex(
            model_name='contentassignment',
            index=models.Index(fields=['student', 'is_active'], name='resources_c_student_1acd87_idx'),
        ),
        migrations.AddIndex(
            model_name='contentassignment',
            index=models.Index(fields=['assigned_by', 'is_active'], name='resources_c_assigne_1e6f41_idx'),
        ),
        migrations.AddIndex(
            model_name='contentassignment',
            index=models.Index(fields=['due_date'], name='resources_c_due_dat_f7e54d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contentassignment',
            unique_together={('content_item', 'student', 'assigned_by_type')},
        ),
        migrations.AddIndex(
            model_name='contentaccesssession',
            index=models.Index(fields=['student', 'content_item'], name='resources_c_student_f45c7e_idx'),
        ),
    ]
