# Generated by Django 4.2.29 on 2026-04-05 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scheduling', '0001_initial'),
        ('classes', '0001_initial'),
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NCDC Lower Secondary CBC Template', max_length=255)),
                ('structure_blob', models.JSONField(default=dict, help_text='Defines display metrics like 20/80 split visuals')),
            ],
        ),
        migrations.CreateModel(
            name='MarkingRubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria_blob', models.JSONField(help_text='Detailed grading logic and criteria weights')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rubric', to='assessments.assessment')),
            ],
        ),
        migrations.CreateModel(
            name='GradeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('teacher_feedback', models.TextField(blank=True, null=True)),
                ('graded_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grade', to='assessments.submission')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formative_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('summative_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('grade_letter', models.CharField(blank=True, max_length=5, null=True)),
                ('descriptor', models.TextField(blank=True, help_text="e.g. 'Basic', 'Moderate', 'Outstanding'", null=True)),
                ('teacher_remarks', models.TextField(blank=True, null=True)),
                ('finalized_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_grades', to='classes.class')),
                ('finalized_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_grades', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_grades', to=settings.AUTH_USER_MODEL)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_grades', to='scheduling.academicterm')),
            ],
            options={
                'unique_together': {('student', 'assigned_class', 'term')},
            },
        ),
        migrations.CreateModel(
            name='ReportCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('overall_grade_letter', models.CharField(blank=True, max_length=5, null=True)),
                ('promotion_status', models.CharField(blank=True, help_text='e.g. Promoted, Repeating', max_length=50, null=True)),
                ('class_teacher_remarks', models.TextField(blank=True, null=True)),
                ('headteacher_remarks', models.TextField(blank=True, null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='report_cards/')),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='institutions.institution')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='grading.reporttemplate')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='scheduling.academicterm')),
            ],
            options={
                'unique_together': {('student', 'term')},
            },
        ),
    ]
