# Generated by Django 4.2.29 on 2026-04-01 21:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
        ('grading', '0002_reportcard_subjectgrade'),
        ('scheduling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectgrade',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_grades', to='scheduling.academicterm'),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='institutions.institution'),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='scheduling.academicterm'),
        ),
        migrations.AlterUniqueTogether(
            name='subjectgrade',
            unique_together={('student', 'assigned_class', 'term')},
        ),
        migrations.AlterUniqueTogether(
            name='reportcard',
            unique_together={('student', 'term')},
        ),
    ]
