# Generated by Django 4.2.29 on 2026-04-02 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0003_subjectgrade_term_reportcard_institution_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NCDC Lower Secondary CBC Template', max_length=255)),
                ('structure_blob', models.JSONField(default=dict, help_text='Defines display metrics like 20/80 split visuals')),
            ],
        ),
        migrations.RemoveField(
            model_name='subjectgrade',
            name='score',
        ),
        migrations.AddField(
            model_name='reportcard',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='report_cards/'),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='promotion_status',
            field=models.CharField(blank=True, help_text='e.g. Promoted, Repeating', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subjectgrade',
            name='descriptor',
            field=models.TextField(blank=True, help_text="e.g. 'Basic', 'Moderate', 'Outstanding'", null=True),
        ),
        migrations.AddField(
            model_name='subjectgrade',
            name='formative_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='subjectgrade',
            name='summative_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='subjectgrade',
            name='total_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='grading.reporttemplate'),
        ),
    ]
