# Generated by Django 6.0.4 on 2026-04-24 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0007_subscriptionplan_learnerregistration_completed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionDiscoveryProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_city', models.CharField(blank=True, max_length=120)),
                ('location_region', models.CharField(blank=True, max_length=120)),
                ('about', models.TextField(blank=True, help_text='Public intro shown on the institution profile page.')),
                ('admission_blurb', models.TextField(blank=True, help_text='What prospective parents should know about applying.')),
                ('boarding_options', models.CharField(blank=True, choices=[('day', 'Day only'), ('boarding', 'Boarding only'), ('day_and_boarding', 'Day and Boarding')], max_length=40)),
                ('admission_status', models.CharField(choices=[('open', 'Admissions Open'), ('invitation_only', 'Invitation Only'), ('waitlist', 'Waitlist'), ('closed', 'Admissions Closed')], default='open', max_length=40)),
                ('levels_offered', models.JSONField(blank=True, default=list, help_text='e.g. ["P1","P7","S1","S6"]')),
                ('subjects_offered', models.JSONField(blank=True, default=list, help_text='Human-readable subject names.')),
                ('admission_contact_name', models.CharField(blank=True, max_length=200)),
                ('admission_contact_email', models.EmailField(blank=True, max_length=254)),
                ('admission_contact_phone', models.CharField(blank=True, max_length=30)),
                ('website', models.URLField(blank=True)),
                ('is_listed', models.BooleanField(default=False, help_text='If False the profile is hidden from the public discovery hub.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discovery_profile', to='institutions.institution')),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionRecommendationScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maple_activeness_score', models.FloatField(default=0)),
                ('growth_index', models.FloatField(default=0)),
                ('verified_lesson_delivery', models.FloatField(default=0)),
                ('assessment_activity', models.FloatField(default=0)),
                ('attendance_tracking', models.FloatField(default=0)),
                ('parent_reporting', models.FloatField(default=0)),
                ('teacher_responsiveness', models.FloatField(default=0)),
                ('peer_learning_activity', models.FloatField(default=0)),
                ('student_engagement', models.FloatField(default=0)),
                ('platform_consistency', models.FloatField(default=0)),
                ('exam_readiness_strength', models.FloatField(default=0)),
                ('standby_teachers_available', models.IntegerField(default=0)),
                ('explanation', models.TextField(blank=True)),
                ('last_computed_at', models.DateTimeField(auto_now=True)),
                ('institution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_score', to='institutions.institution')),
            ],
            options={
                'ordering': ['-maple_activeness_score', '-growth_index'],
            },
        ),
    ]
