# Generated by Django 6.0.4 on 2026-04-26 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution_discovery', '0001_initial'),
        ('institutions', '0007_subscriptionplan_learnerregistration_completed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionMatchEligibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified', models.BooleanField(default=False)),
                ('safeguarding_approved', models.BooleanField(default=False)),
                ('admission_open', models.BooleanField(default=False)),
                ('activeness_score', models.FloatField(db_index=True, default=0)),
                ('minimum_activity_met', models.BooleanField(default=False)),
                ('can_view_student_matches', models.BooleanField(db_index=True, default=False)),
                ('can_send_invitations', models.BooleanField(db_index=True, default=False)),
                ('notes', models.TextField(blank=True, help_text='Why view/invite was granted or revoked.')),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('institution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='match_eligibility', to='institutions.institution')),
            ],
            options={
                'verbose_name': 'Institution match eligibility',
            },
        ),
        migrations.CreateModel(
            name='InstitutionStudentInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitation_type', models.CharField(choices=[('apply', 'Invite to apply'), ('interview', 'Invite for interview'), ('entrance_assessment', 'Invite for entrance assessment'), ('school_visit', 'Invite for school visit'), ('preview_class', 'Invite to preview class'), ('scholarship', 'Offer scholarship/bursary'), ('boarding_admission', 'Boarding admission discussion'), ('passport_access_request', 'Request Learning Passport access'), ('information_request', 'Request more information')], max_length=32)),
                ('message', models.TextField(blank=True)),
                ('why_interested', models.JSONField(blank=True, default=list, help_text='Bullet reasons surfaced to the parent on the invitation card.')),
                ('requested_share_level', models.CharField(choices=[('anonymous_summary', 'Anonymous summary'), ('academic_summary', 'Academic summary'), ('passport_summary', 'Passport summary'), ('full_passport', 'Full Learning Passport')], default='academic_summary', max_length=24)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('viewed', 'Viewed'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired'), ('application_started', 'Application started'), ('application_submitted', 'Application submitted'), ('interview_scheduled', 'Interview scheduled'), ('offer_made', 'Offer made'), ('enrolled', 'Enrolled')], db_index=True, default='sent', max_length=30)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_school_invitations', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to='institutions.institution')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_parent_invitations', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_school_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PassportAccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_sections', models.JSONField(default=list, help_text='List of section keys (see SECTION_CHOICES).')),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined'), ('expired', 'Expired'), ('revoked', 'Revoked')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passport_access_requests', to='institutions.institution')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_passport_access_requests', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passport_access_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentOpportunityPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_approved', models.BooleanField(db_index=True, default=False)),
                ('visibility_status', models.CharField(choices=[('private', 'Private — institutions cannot discover me'), ('recommended_only', 'I see schools, but schools cannot contact me'), ('open_to_contact', 'Verified institutions can send invitations')], db_index=True, default='private', max_length=24)),
                ('open_to_institution_contact', models.BooleanField(default=False)),
                ('open_to_scholarships', models.BooleanField(default=False)),
                ('open_to_boarding', models.BooleanField(default=False)),
                ('open_to_day', models.BooleanField(default=True)),
                ('open_to_school_visit_invites', models.BooleanField(default=False)),
                ('open_to_preview_class_invites', models.BooleanField(default=False)),
                ('national_search_only', models.BooleanField(default=False, help_text='When true, only institutions in the same country surface the learner.')),
                ('preferred_countries', models.JSONField(blank=True, default=list)),
                ('preferred_regions', models.JSONField(blank=True, default=list)),
                ('preferred_curriculum', models.CharField(blank=True, max_length=64)),
                ('preferred_entry_level', models.CharField(blank=True, max_length=64)),
                ('preferred_entry_term', models.CharField(blank=True, max_length=32)),
                ('preferred_study_mode', models.CharField(choices=[('day', 'Day only'), ('boarding', 'Boarding only'), ('any', 'Either day or boarding')], default='any', max_length=12)),
                ('share_level', models.CharField(choices=[('anonymous_summary', 'Anonymous summary'), ('academic_summary', 'Academic summary'), ('passport_summary', 'Passport summary'), ('full_passport', 'Full Learning Passport')], default='anonymous_summary', help_text='Maximum data the learner is willing to share BEFORE per-request consent.', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent who recorded the approval. Required for minors.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_opportunity_preferences', to=settings.AUTH_USER_MODEL)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student opportunity preference',
            },
        ),
        migrations.CreateModel(
            name='StudentReadinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=2)),
                ('curriculum', models.CharField(blank=True, max_length=64)),
                ('class_level', models.CharField(blank=True, max_length=32)),
                ('region', models.CharField(blank=True, max_length=64)),
                ('activity_score', models.FloatField(default=0)),
                ('academic_score', models.FloatField(default=0)),
                ('improvement_score', models.FloatField(default=0)),
                ('exam_readiness_score', models.FloatField(default=0)),
                ('project_score', models.FloatField(default=0)),
                ('teacher_feedback_score', models.FloatField(default=0)),
                ('parent_engagement_score', models.FloatField(default=0)),
                ('overall_readiness_score', models.FloatField(db_index=True, default=0)),
                ('average_score_pct', models.FloatField(default=0, help_text='Average across all subjects, 0..100. Lane A gate (>=70).')),
                ('improvement_pct_6w', models.FloatField(default=0, help_text='Improvement over the last 6 weeks, percentage points. Lane B gate (>=15).')),
                ('parent_engaged', models.BooleanField(default=False, help_text='Whether the parent meets the parent-engagement signal that gates Lane B.')),
                ('lane', models.CharField(choices=[('high_performer', 'High academic performer'), ('high_growth', 'High-growth learner'), ('not_eligible', 'Not eligible for institution discovery')], db_index=True, default='not_eligible', max_length=20)),
                ('eligible', models.BooleanField(db_index=True, default=False)),
                ('last_calculated_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='readiness_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student readiness profile',
                'ordering': ['-overall_readiness_score'],
            },
        ),
        migrations.CreateModel(
            name='StudentInstitutionMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.FloatField(db_index=True, default=0)),
                ('match_reasons', models.JSONField(blank=True, default=list)),
                ('student_readiness_snapshot', models.JSONField(blank=True, default=dict)),
                ('institution_strength_snapshot', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('suggested_to_student', 'Suggested to student'), ('suggested_to_institution', 'Suggested to institution'), ('student_hidden', 'Hidden by student'), ('institution_hidden', 'Hidden by institution'), ('invited', 'Invited'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('applied', 'Applied'), ('enrolled', 'Enrolled'), ('expired', 'Expired')], db_index=True, default='suggested_to_institution', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_matches', to='institutions.institution')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institution_matches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student↔institution match',
                'ordering': ['-match_score'],
                'unique_together': {('student', 'institution')},
            },
        ),
    ]
