# Generated by Django 6.0.4 on 2026-04-26 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution_discovery', '0002_institutionmatcheligibility_and_more'),
        ('institutions', '0007_subscriptionplan_learnerregistration_completed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScholarshipOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('kind', models.CharField(choices=[('academic', 'Academic merit'), ('financial_need', 'Financial need'), ('exam_candidate', 'Exam candidate support'), ('boarding', 'Boarding scholarship'), ('girl_child_stem', 'Girl-child STEM'), ('orphan', 'Orphan / vulnerable learner'), ('high_performer', 'High-performing learner award'), ('other', 'Other')], default='academic', max_length=24)),
                ('amount_band', models.CharField(choices=[('partial_25', 'Partial — 25%'), ('partial_50', 'Partial — 50%'), ('partial_75', 'Partial — 75%'), ('full', 'Full scholarship'), ('stipend', 'Stipend / allowance'), ('custom', 'Custom — see description')], default='partial_50', max_length=24)),
                ('target_class_levels', models.JSONField(blank=True, default=list, help_text='List of class level codes the scholarship is open to.')),
                ('target_subjects', models.JSONField(blank=True, default=list)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('seats_available', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scholarship_opportunities_created', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarship_opportunities', to='institutions.institution')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
