# Generated by Django 4.2.29 on 2026-04-08 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interventions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterventionEffectivenessTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baseline_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('post_intervention_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('student_engagement_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Did the student actually open the plan resources?', max_digits=5)),
                ('parent_followup_logged', models.BooleanField(default=False)),
                ('outcome_roi_pct', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('intervention_plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='effectiveness_tracker', to='interventions.interventionplan')),
            ],
        ),
    ]
