import os
import io
import logging
from google.oauth2 import service_account
from googleapiclient.discovery import build
from googleapiclient.http import MediaIoBaseDownload

logger = logging.getLogger(__name__)

class GoogleWorkspaceService:
    def __init__(self):
        self.scopes = [
            'https://www.googleapis.com/auth/admin.reports.audit.readonly',
            'https://www.googleapis.com/auth/drive.readonly',
            'https://www.googleapis.com/auth/meetings.space.readonly' 
        ]
        # In a real deployed app, point to a json file via env var
        self.creds_file = os.getenv('GOOGLE_APPLICATION_CREDENTIALS', None)
        # Usually requires domain wide delegation for full access across enterprise
        self.subject = os.getenv('GOOGLE_WORKSPACE_ADMIN_EMAIL', None)

    def _get_credentials(self):
        if not self.creds_file:
            raise ValueError("Google Application Credentials not configured.")
        return service_account.Credentials.from_service_account_file(
            self.creds_file,
            scopes=self.scopes,
            subject=self.subject
        )

    def get_meeting_recording_file_id(self, meeting_code: str):
        """
        Attempts to locate the Drive File ID for the recording of the given Google Meet.
        Since standard Google Workspace APIs don't directly map 'Meet Code' to 'Recording',
        the most robust way (with Domain Wide Delegation) is to query Google Drive for files
        generated by the Meet service matching the expected recording naming convention,
        or querying the Meet REST API conference records.
        """
        try:
            creds = self._get_credentials()
            drive_service = build('drive', 'v3', credentials=creds)
            # A common search tactic for Meet recordings
            query = f"mimeType='video/mp4' and name contains '{meeting_code}' and trashed = false"
            results = drive_service.files().list(
                q=query,
                spaces='drive',
                fields='files(id, name, createdTime)',
                orderBy='createdTime desc',
                pageSize=1
            ).execute()
            
            items = results.get('files', [])
            if not items:
                logger.warning(f"No recording found for meeting code: {meeting_code}")
                return None
                
            return items[0]['id']

        except Exception as e:
            logger.error(f"Error querying Google Drive for Meet link {meeting_code}: {e}")
            raise e

    def download_drive_file(self, file_id: str, destination_path: str):
        """
        Downloads a file from Google Drive into a local secure path.
        """
        try:
            creds = self._get_credentials()
            drive_service = build('drive', 'v3', credentials=creds)
            
            request = drive_service.files().get_media(fileId=file_id)
            fh = io.FileIO(destination_path, 'wb')
            downloader = MediaIoBaseDownload(fh, request)
            
            done = False
            while done is False:
                status, done = downloader.next_chunk()
                # print("Download %d%%." % int(status.progress() * 100))
                
            logger.info(f"Successfully downloaded Drive file {file_id} to {destination_path}")
            return True

        except Exception as e:
            logger.error(f"Failed to download Google Drive file {file_id}: {e}")
            raise e
