"""
Django settings for edify_core project.

Generated by 'django-admin startproject' using Django 4.2.29.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
import sys
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Add apps directory to Python path
sys.path.insert(0, os.path.join(BASE_DIR, 'apps'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'true').lower() in ('1', 'true', 'yes', 'on')

# SECURITY WARNING: keep the secret key used in production secret!
# In DEBUG mode we fall back to the historical dev key so local workflows and
# existing test fixtures keep working. In production DJANGO_SECRET_KEY must be
# supplied; we raise loudly if it is missing so nothing silently deploys with
# the insecure default.
_DEV_INSECURE_SECRET = 'django-insecure-pcbj15-f@m)2vi&5#elyp)-wvclek=saa$ceubch&a#=38kr%y'
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY') or (_DEV_INSECURE_SECRET if DEBUG else '')
if not SECRET_KEY:
    raise RuntimeError(
        'DJANGO_SECRET_KEY is required when DEBUG=False. Generate one via: '
        'python -c "from django.core.management.utils import get_random_secret_key; '
        'print(get_random_secret_key())"'
    )

ALLOWED_HOSTS = [h.strip() for h in os.environ.get('DJANGO_ALLOWED_HOSTS', '').split(',') if h.strip()]
if DEBUG and not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1', '[::1]', 'testserver']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third Party Apps
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'django_filters',
    
    # Internal Apps
    'accounts.apps.AccountsConfig',
    'institutions.apps.InstitutionsConfig',
    'curriculum.apps.CurriculumConfig',
    'classes.apps.ClassesConfig',
    'lessons.apps.LessonsConfig',
    'resources.apps.ResourcesConfig',
    'assessments.apps.AssessmentsConfig',
    'grading.apps.GradingConfig',
    'marketplace.apps.MarketplaceConfig',
    'live_sessions.apps.LiveSessionsConfig',
    'discussions.apps.DiscussionsConfig',
    'tutoring.apps.TutoringConfig',
    'interventions.apps.InterventionsConfig',
    'exams.apps.ExamsConfig',
    'parent_portal.apps.ParentPortalConfig',
    'notifications.apps.NotificationsConfig',
    'analytics.apps.AnalyticsConfig',
    'ai_services.apps.AiServicesConfig',
    'scheduling.apps.SchedulingConfig',
    'attendance.apps.AttendanceConfig',
    'intelligence.apps.IntelligenceConfig',
    'diagnostics.apps.DiagnosticsConfig',
    'institution_discovery.apps.InstitutionDiscoveryConfig',
    'mastery.apps.MasteryConfig',
    'practice_labs.apps.PracticeLabsConfig',
    'mastery_projects.apps.MasteryProjectsConfig',
    'mentor_reviews.apps.MentorReviewsConfig',
    'passport.apps.PassportConfig',
    'exam_simulator.apps.ExamSimulatorConfig',
    'admission_passport.apps.AdmissionPassportConfig',
    'standby_teachers.apps.StandbyTeachersConfig',
    'cohorts.apps.CohortsConfig',
    'pathways.apps.PathwaysConfig',
    'learner_settings.apps.LearnerSettingsConfig',
    'pilot_payments.apps.PilotPaymentsConfig',
    'fees.apps.FeesConfig',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    # Whitenoise serves collected static files directly from the gunicorn
    # process. No-op when running `runserver` in dev (staticfiles app wins),
    # active in prod/Docker where collectstatic populates STATIC_ROOT.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'edify_core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'edify_core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
#
# Local dev: no DATABASE_URL -> fall back to the committed sqlite file.
# Docker / prod: DATABASE_URL=postgres://... is parsed into a full config.
_DATABASE_URL = os.environ.get('DATABASE_URL')
if _DATABASE_URL:
    import dj_database_url
    DATABASES = {
        'default': dj_database_url.parse(_DATABASE_URL, conn_max_age=600, ssl_require=False),
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'  # populated by `manage.py collectstatic` in Docker / prod
# Manifest storage requires `collectstatic` to have run and produces broken
# URLs if a template references a file that isn't in the manifest. In DEBUG
# we use Django's default so `runserver` works without a collectstatic step.
if not DEBUG:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Custom User Model
AUTH_USER_MODEL = 'accounts.User'

# Authentication Backends
AUTHENTICATION_BACKENDS = [
    'edify_core.backends.DualAuthenticationBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    # Throttling defaults. AllowAny endpoints (register, onboarding) carry a
    # stricter ScopedRateThrottle — see apps.accounts.views.
    'DEFAULT_THROTTLE_CLASSES': (
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ),
    'DEFAULT_THROTTLE_RATES': {
        'anon': '60/min',
        'user': '600/min',
        'registration': '20/hour',
    },
}

# Email verification gate. When True, JWT issuance requires a verified email.
# Default False in dev so local workflows and the existing test suite keep
# running; flip to True in production via env var.
REQUIRE_EMAIL_VERIFICATION = os.environ.get('REQUIRE_EMAIL_VERIFICATION', 'false').lower() in ('1', 'true', 'yes', 'on')

# Email backend: console in dev so activation links show up in the server log;
# real SMTP in prod via env vars.
EMAIL_BACKEND = os.environ.get(
    'DJANGO_EMAIL_BACKEND',
    'django.core.mail.backends.console.EmailBackend' if DEBUG else 'django.core.mail.backends.smtp.EmailBackend',
)
EMAIL_HOST = os.environ.get('DJANGO_EMAIL_HOST', 'localhost')
EMAIL_PORT = int(os.environ.get('DJANGO_EMAIL_PORT', '25'))
EMAIL_HOST_USER = os.environ.get('DJANGO_EMAIL_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('DJANGO_EMAIL_PASSWORD', '')
EMAIL_USE_TLS = os.environ.get('DJANGO_EMAIL_USE_TLS', 'true').lower() in ('1', 'true', 'yes', 'on')
DEFAULT_FROM_EMAIL = os.environ.get('DJANGO_FROM_EMAIL', 'no-reply@maple.edify')
# Base URL used to construct links in activation emails (frontend route).
FRONTEND_BASE_URL = os.environ.get('FRONTEND_BASE_URL', 'http://localhost:5173')

from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}

# CORS Configuration
# Wide-open in dev; in prod the origin list must be supplied explicitly.
CORS_ALLOW_ALL_ORIGINS = DEBUG
CORS_ALLOWED_ORIGINS = [o.strip() for o in os.environ.get('DJANGO_CORS_ORIGINS', '').split(',') if o.strip()]
CORS_ALLOW_CREDENTIALS = True

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Structured logging. JSON in prod (machine-parseable for log aggregators);
# human-readable in dev. Everything routes to stdout; deployment layer can
# tail or ship further.
_LOG_FORMAT_JSON = (
    '{"time":"%(asctime)s","level":"%(levelname)s","logger":"%(name)s",'
    '"module":"%(module)s","message":"%(message)s"}'
)
_LOG_FORMAT_HUMAN = '[%(asctime)s] %(levelname)s %(name)s: %(message)s'
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'json': {'format': _LOG_FORMAT_JSON},
        'human': {'format': _LOG_FORMAT_HUMAN},
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'human' if DEBUG else 'json',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'DEBUG' if DEBUG else 'INFO',
    },
    'loggers': {
        'django': {'handlers': ['console'], 'level': 'INFO', 'propagate': False},
        'django.request': {'handlers': ['console'], 'level': 'WARNING', 'propagate': False},
        'edify': {'handlers': ['console'], 'level': 'DEBUG' if DEBUG else 'INFO', 'propagate': False},
    },
}

# CELERY CONFIGURATION
# Production-ready Celery settings with fallback to local defaults
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # Avoid hung tasks (30 mins limits)
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True

# Disable eager execution by default for true async behavior, uncomment for local non-Redis dev
CELERY_TASK_ALWAYS_EAGER = True

# Caching for Dashboard Metrics
CACHES = {
    'default': {
        # Using LocMemCache for local dev to avoid crash if Redis isn't running
        # Change to 'django.core.cache.backends.redis.RedisCache' in production
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}

# Media Files Configuration (for user uploads)
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# File Upload Settings
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 100 * 1024 * 1024  # 100MB (for large video files)
FILE_UPLOAD_PERMISSIONS = 0o644
FILE_UPLOAD_TEMP_DIR = os.path.join(BASE_DIR, 'tmp')

# Ensure upload directories exist
os.makedirs(MEDIA_ROOT, exist_ok=True)
os.makedirs(FILE_UPLOAD_TEMP_DIR, exist_ok=True)

# --- Error tracking (Sentry) -------------------------------------
# Env-gated: if SENTRY_DSN is unset, initialization is skipped entirely.
# No network calls, no import cost in local dev or tests.
_SENTRY_DSN = os.environ.get('SENTRY_DSN', '').strip()
if _SENTRY_DSN and not DEBUG:
    try:
        import sentry_sdk
        from sentry_sdk.integrations.django import DjangoIntegration
        sentry_sdk.init(
            dsn=_SENTRY_DSN,
            integrations=[DjangoIntegration()],
            # Conservative sampling — pilot has low volume; increase post-launch.
            traces_sample_rate=0.1,
            send_default_pii=False,
            environment=os.environ.get('SENTRY_ENVIRONMENT', 'production'),
            release=os.environ.get('GIT_SHA', ''),
        )
    except ImportError:
        # sentry-sdk not installed — don't crash the app for this.
        pass
