# Generated by Django 4.2.29 on 2026-04-08 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_offlineacademicresult_nationalexamresult'),
        ('scheduling', '0002_timetableslot_is_draft_timetableslot_subject_and_more'),
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_cancelled', models.BooleanField(default=False)),
                ('lesson_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lessons.lesson')),
                ('timetable_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='scheduling.timetableslot')),
            ],
        ),
        migrations.CreateModel(
            name='LessonVerificationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('reminder_sent', 'Reminder Sent'), ('acknowledged', 'Acknowledged'), ('started', 'Started'), ('completed', 'Completed'), ('unverified', 'Unverified / Missed'), ('partially_verified', 'Partially Verified')], default='scheduled', max_length=30)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('lesson_instance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification_record', to='lessons.lessoninstance')),
                ('linked_assignment', models.ForeignKey(blank=True, help_text='Required to move from started to completed', null=True, on_delete=django.db.models.deletion.SET_NULL, to='assessments.assessment')),
            ],
        ),
    ]
