# Generated by Django 4.2.29 on 2026-04-08 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
        ('curriculum', '0003_academicyear'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0001_initial'),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcosystemComparisonSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('inst_teacher_activity_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('indep_teacher_activity_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('inst_student_engagement_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('indep_student_engagement_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('inst_resource_access_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('indep_resource_access_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='PlatformGrowthFunnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('institutions_onboarded', models.IntegerField(default=0)),
                ('institutions_activated', models.IntegerField(default=0)),
                ('institutions_dormant', models.IntegerField(default=0)),
                ('institutions_at_risk', models.IntegerField(default=0)),
                ('teachers_onboarded', models.IntegerField(default=0)),
                ('teachers_activated', models.IntegerField(default=0)),
                ('students_onboarded', models.IntegerField(default=0)),
                ('students_activated', models.IntegerField(default=0)),
                ('parents_linked', models.IntegerField(default=0)),
                ('parents_active', models.IntegerField(default=0)),
                ('independent_signups', models.IntegerField(default=0)),
                ('independent_active', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceEffectivenessSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_id', models.CharField(db_index=True, max_length=255)),
                ('resource_type', models.CharField(max_length=50)),
                ('total_opens', models.IntegerField(default=0)),
                ('average_read_time_seconds', models.IntegerField(default=0)),
                ('completion_rate_pct', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('correlation_outcome_lift', models.DecimalField(decimal_places=2, default=0.0, help_text='Estimated % score lift after usage', max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='ParentEngagementIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dashboard_logins_last_30d', models.IntegerField(default=0)),
                ('alert_view_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('intervention_response_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('associated_student_performance_lift', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_index', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionHealthScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_attendance_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('teacher_activity_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('assignment_completion_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('resource_engagement_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('parent_engagement_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('online_offline_translation_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('composite_health_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('status', models.CharField(choices=[('highly_active', 'Highly Active'), ('active', 'Active'), ('moderate', 'Moderate Activity'), ('low', 'Low Activity'), ('dormant', 'Dormant'), ('churn_risk', 'Churn Risk')], default='moderate', max_length=50)),
                ('last_computed', models.DateTimeField(auto_now=True)),
                ('institution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_score', to='institutions.institution')),
            ],
        ),
        migrations.CreateModel(
            name='InsightStoryCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('maple_admin', 'Maple Admin'), ('institution', 'Institution'), ('teacher', 'Teacher')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('impact_level', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20)),
                ('category', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institutions.institution')),
            ],
        ),
        migrations.CreateModel(
            name='EnhancedTeacherEffectivenessIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_independent', models.BooleanField(default=False)),
                ('student_improvement_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('intervention_success_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('class_attendance_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('student_support_responsiveness_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('composite_effectiveness_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='effectiveness_index', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectDifficultySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_mastery_pct', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('dropout_avoidance_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('intervention_frequency', models.IntegerField(default=0)),
                ('is_critical_difficulty', models.BooleanField(default=False)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institutions.institution')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.subject')),
            ],
            options={
                'unique_together': {('subject', 'institution')},
            },
        ),
        migrations.CreateModel(
            name='ClassActivitySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('attendance_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('assignment_completion_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('resource_open_count', models.IntegerField(default=0)),
                ('live_sessions_attended', models.IntegerField(default=0)),
                ('overall_engagement_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('class_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_snapshots', to='classes.class')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.institution')),
            ],
            options={
                'unique_together': {('class_reference', 'date')},
            },
        ),
    ]
