# Generated by Django 4.2.29 on 2026-04-01 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('institutions', '0002_alter_institutionmembership_role'),
        ('curriculum', '0001_initial'),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('event_name', models.CharField(db_index=True, max_length=100)),
                ('country_code', models.CharField(blank=True, max_length=10)),
                ('class_level_id', models.CharField(blank=True, max_length=100)),
                ('topic_id', models.CharField(blank=True, max_length=100)),
                ('object_type', models.CharField(blank=True, max_length=100)),
                ('object_id', models.CharField(blank=True, max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institutions.institution')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='curriculum.subject')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyInstitutionMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('total_students', models.IntegerField(default=0)),
                ('total_teachers', models.IntegerField(default=0)),
                ('student_teacher_ratio', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('average_attendance_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('lessons_published_count', models.IntegerField(default=0)),
                ('fee_collection_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('outstanding_invoices_count', models.IntegerField(default=0)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.institution')),
            ],
            options={
                'unique_together': {('date', 'institution')},
            },
        ),
        migrations.CreateModel(
            name='DailyPlatformMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('total_active_users', models.IntegerField(default=0)),
                ('dau', models.IntegerField(default=0, help_text='Daily Active Users')),
                ('active_institutions', models.IntegerField(default=0)),
                ('paying_institutions', models.IntegerField(default=0)),
                ('live_classes_held', models.IntegerField(default=0)),
                ('lessons_completed', models.IntegerField(default=0)),
                ('assessments_submitted', models.IntegerField(default=0)),
                ('mrr', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('marketplace_gmv', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('payout_liabilities', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('exam_registrations_pending', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectPerformanceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('exam_readiness_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('completion_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('is_at_risk', models.BooleanField(default=False)),
                ('last_computed', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institutions.institution')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_snapshots', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.subject')),
            ],
            options={
                'unique_together': {('student', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='SystemHealthSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('celery_queue_depth', models.IntegerField(default=0)),
                ('failed_background_jobs', models.IntegerField(default=0)),
                ('offline_sync_backlog', models.IntegerField(default=0)),
                ('average_db_latency_ms', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='SubjectPerformanceAggregate',
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['event_name', 'occurred_at'], name='analytics_a_event_n_aeeca0_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['institution', 'occurred_at'], name='analytics_a_institu_a3c2b5_idx'),
        ),
    ]
