# Generated by Django 4.2.29 on 2026-04-02 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0004_teacherqualityscore_subscriptionledger_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0002_analyticsevent_dailyinstitutionmetric_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherPerformanceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baseline_difficulty_score', models.DecimalField(decimal_places=2, default=50.0, help_text='Average historic score of this cohort', max_digits=5)),
                ('class_average_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('live_sessions_delivered', models.IntegerField(default=0)),
                ('assignments_published', models.IntegerField(default=0)),
                ('interventions_resolved', models.IntegerField(default=0)),
                ('last_computed', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.institution')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_performance_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherAttendanceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('was_present_offline', models.BooleanField(default=True, help_text='Manual headteacher log')),
                ('online_sessions_completed', models.IntegerField(default=0)),
                ('late_starts', models.IntegerField(default=0)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.institution')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('date', 'teacher')},
            },
        ),
    ]
